### ISSUE TITLE
 Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Megavolv** [iron-fish/ironfish#847] opened 2021-12-31 20:07 UTC
Hello!
Ive got new error:

Mining block 46429 on request 34168... ⡿ 1978528 H/s

<--- Last few GCs --->

[384136:0x65c4210] 63980366 ms: Mark-sweep 3855.1 (4130.2) -> 3842.0 (4130.4) MB, 3772.1 / 0.0 ms  (average mu = 0.347, current mu = 0.329) task scavenge might not succeed
[384136:0x65c4210] 63985918 ms: Mark-sweep 3855.3 (4130.4) -> 3842.2 (4130.7) MB, 3696.3 / 0.0 ms  (average mu = 0.341, current mu = 0.334) task scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb00d90 node::Abort() [node]
 2: 0xa1823b node::FatalError(char const*, char const*) [node]
 3: 0xcedbce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcedf47 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xea6105  [node]
 6: 0xea6be6  [node]
 7: 0xeb4b1e  [node]
 8: 0xeb5560 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf18aa4 v8::internal::ScavengeJob::Task::RunInternal() [node]
10: 0xdabeeb non-virtual thunk to v8::internal::CancelableTask::Run() [node]
11: 0xb6e964 node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) [node]
12: 0xb707c9 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [node]
13: 0x155a336  [node]
14: 0x156c7a4  [node]
15: 0x155ac68 uv_run [node]
16: 0xa3dfe5 node::SpinEventLoop(node::Environment*) [node]
17: 0xb42dc6 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [node]
18: 0xac4812 node::Start(int, char**) [node]
19: 0x7f567c08d0b3 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
20: 0xa3bf3c  [node]
/home/peter/ironfish/ironfish-cli/bin/ironfish: line 45: 384136 Aborted                 (core dumped) "$NODE" "$DIR/run" "$@"

**Comment by wd021** [comment] 2022-03-02 21:50
just hit this on v0.1.25 as well

**Comment by crProductGuy** [comment] 2022-03-11 08:07
I saw this too:

Saw this from Mining terminal window after many days of successful mining runs.

Environment:

2015 2-core 2.7 GHz Core i5 MacBook Pro running MacOS Monterrey 12.1
8GB RAM
Not doing anything else in foreground except Iron Fish node + miner
 - some Carbon Copy Cloner disc clone jobs (uses rsync) overnight.
 - some Time Machine backups when the system was in the mood

Otherwise only running NordVPN and Iron Fish node + miner, installed via Brew.

Ironfish 0.1.23 with Telemetry enabled
From `ironfish status`
Version              0.1.23 @ 0e9e22f



Node                 STARTED

Heap Used            362.03 MiB / 396.67 MiB


Memory               647.46 MiB


 ironfish miners:start -t -1

Starting to mine with 4 threads

Mining block 131261 on request 58357... ⣯ 3.43 MH/s (3437752)

^C

<username> % ironfish miners:start -t -1

Starting to mine with 4 threads

Mining block 138916 on request 93214... ⡿ 2.55 MH/s (2552914)



<--- Last few GCs --->



[4848:0x7fb1f9300000] 30535091 ms: Mark-sweep 1920.0 (2083.0) -> 1907.0 (2083.5) MB, 4343.7 / 0.0 ms  (average mu = 0.388, current mu = 0.385) task scavenge might not succeed

[4848:0x7fb1f9300000] 30541675 ms: Mark-sweep 1920.3 (2083.5) -> 1907.4 (2083.7) MB, 4042.5 / 0.0 ms  (average mu = 0.387, current mu = 0.386) task scavenge might not succeed





<--- JS stacktrace --->



FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

 1: 0x108388175 node::Abort() [/usr/local/Cellar/node@16/16.14.0/bin/node]

 2: 0x1083882f7 node::OnFatalError(char const*, char const*) [/usr/local/Cellar/node@16/16.14.0/bin/node]

 3: 0x1084c53f9 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node@16/16.14.0/bin/node]

 4: 0x1084c53a3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node@16/16.14.0/bin/node]

 5: 0x1085ee91f v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/Cellar/node@16/16.14.0/bin/node]

 6: 0x1085f149c v8::internal::Heap::MarkCompactPrologue() [/usr/local/Cellar/node@16/16.14.0/bin/node]

 7: 0x1085eef4f v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/Cellar/node@16/16.14.0/bin/node]

 8: 0x1085ed401 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/Cellar/node@16/16.14.0/bin/node]

 9: 0x10864a534 v8::internal::ScavengeJob::Task::RunInternal() [/usr/local/Cellar/node@16/16.14.0/bin/node]

10: 0x1083e1bba node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/usr/local/Cellar/node@16/16.14.0/bin/node]

11: 0x1083e0c53 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/usr/local/Cellar/node@16/16.14.0/bin/node]

12: 0x10a7df1f1 uv__async_io [/usr/local/Cellar/libuv/1.43.0/lib/libuv.1.dylib]

13: 0x10a7eef8c uv__io_poll [/usr/local/Cellar/libuv/1.43.0/lib/libuv.1.dylib]

14: 0x10a7df61c uv_run [/usr/local/Cellar/libuv/1.43.0/lib/libuv.1.dylib]

15: 0x1082d1fc3 node::SpinEventLoop(node::Environment*) [/usr/local/Cellar/node@16/16.14.0/bin/node]

16: 0x1083c0abb node::NodeMainInstance::Run(int*, node::Environment*) [/usr/local/Cellar/node@16/16.14.0/bin/node]

17: 0x1083c074e node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/usr/local/Cellar/node@16/16.14.0/bin/node]

18: 0x10835d2c9 node::Start(int, char**) [/usr/local/Cellar/node@16/16.14.0/bin/node]

19: 0x1102a74fe 

/usr/local/bin/ironfish: line 46:  4848 Abort trap: 6           "$NODE" "$DIR/run" "$@"

**Comment by Shekelme** [comment] 2022-06-18 16:53
```
<--- Last few GCs --->

[429429:0x4ea36c0] 35236784 ms: Mark-sweep 4026.0 (4130.7) -> 4010.9 (4131.5) MB, 2092.4 / 0.2 ms  (average mu = 0.244, current mu = 0.122) allocation failure scavenge might not succeed
[429429:0x4ea36c0] 35239217 ms: Mark-sweep 4027.0 (4131.7) -> 4011.5 (4132.5) MB, 2232.2 / 0.1 ms  (average mu = 0.168, current mu = 0.083) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09c10 node::Abort() [node]
 2: 0xa1c193 node::FatalError(char const*, char const*) [node]
 3: 0xcf8dde v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcf9157 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xeb09f5  [node]
 6: 0xeb14d6  [node]
 7: 0xebf9fe  [node]
 8: 0xec0440 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xec33be v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xe848fa v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x11fd646 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x15f20b9  [node]
```

Version 0.1.36 @ 6dfc736

**Comment by rolltable** [comment] 2022-06-29 05:02
Thanks for the bug report, we haven't tracked down this memory leak yet.

**Comment by NullSoldier** [comment] 2022-06-29 05:02
Thanks for the report. We haven't tracked down this memory issue yet.

**Comment by Shekelme** [comment] 2022-07-22 10:09
v0.1.39, still the same error.

**Comment by lwisne** [comment] 2022-08-03 23:34
Duplicate of https://github.com/iron-fish/ironfish/issues/1925

**Closed by lwisne** 2022-08-03 23:34 UTC
Labels: bug, verified
