### ISSUE TITLE
Deposit is done, but transaction not found in the explorer

### ISSUE THREAD

**Issue by GoUpToDream** [iron-fish/ironfish#1724] opened 2022-07-03 07:40 UTC
### What happened?

I sent ironfish deposit. The transaction was done.  But the transaction wasn't found in the explorer and wasn't displayed on the leaderboard. 

ironfish deposit
yarn run v1.22.19
$ yarn build && yarn start:js deposit
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run deposit

You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000001 ($ORE 1) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 47.28539748 ($ORE 4,728,539,748).
The memo will contain the graffiti "SunBird".

* This action is NOT reversible *

Do you confirm (Y/N)?: y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Depositing $IRON 0.10000000 ($ORE 10,000,000) from SunBird
Transaction Hash: 0c2b0271f52df1930d9ef0b726ecc9cf52971810693076db18fbb4302d19ca99
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/0c2b0271f52df1930d9ef0b726ecc9cf52971810693076db18fbb4302d19ca99 (it can take a few minutes before the transaction appears in the Explorer)
Done in 1143.08s.

![image](https://user-images.githubusercontent.com/79373364/177030060-c0eed2fc-86dc-4487-bfe6-af1d6e78ef5e.png)

### Version

 v0.1.37

### Graffiti

SunBird

**Comment by lwisne** [comment] 2022-08-03 17:04
This is likely due to transactions not being picked up due to too low of fees + a poor UI into expired transactions.

Duplicate of https://github.com/iron-fish/ironfish/issues/1727

See thread there for more info, and the plan to fix.

We are working on this - you will be able to easily send your funds again soon!

**Closed by lwisne** 2022-08-03 17:04 UTC
Labels: bug
