### ISSUE TITLE
zero balance and `accounts:rescan` not scanning

### ISSUE THREAD

**Issue by terrancewong** [iron-fish/ironfish#1520] opened 2022-05-27 05:40 UTC
### What happened?

``` shell
$ node ./ironfish-cli/bin/run accounts:rescan -v --reset
Connecting to /home/asdf/.ironfish/ironfish.ipc
Rescanning Transactions... ⡿ Asking node to start scanning
```

in another terminal
```shell
$ ironfish workers:status -f 
. . .
Workers: STARTED - 0 -> 0 / 48 - -0.49 jobs Δ, 27.49 jobs/s  

JOB                  | QUEUE | EXECUTE | ERROR | DONE
BoxMessage           |     0 |       0 |     0 | 2950
CreateMinersFee      |     0 |       0 |     0 | 0
CreateTransaction    |     0 |       0 |     0 | 0
GetUnspentNotes      |     0 |       0 |     0 | 0
SubmitTelemetry      |     0 |       0 |     0 | 9
UnboxMessage         |     0 |       0 |     0 | 271
VerifyTransaction    |     0 |       0 |     0 | 19901
```

looks like it's just doing nothing, and refuse to rescan. this node is just freshly synced. 

whatever command arguments `--reset` or go offline then `--local`. it just won't scan. 

`rm -r ~/.ironfish/index  ~/.ironfish/accounts`, then `chain:repair`, still no scanning.

`accounts:balance` any accounts, returns 0 very quickly.

### Version

v0.1.35

### Graffiti

bh9sqoCqIR3rDFstCCCw1g

**Comment by lwisne** [comment] 2022-08-01 20:02
Did this ever clear up for you?

**Comment by lwisne** [comment] 2022-08-01 21:52
probably this: https://github.com/iron-fish/ironfish/issues/1520

**Comment by lwisne** [comment] 2022-08-01 21:54
duplicate of 1556

**Closed** 2022-08-01 21:54 UTC
Labels: bug, verified, needs verification
