### ISSUE TITLE
No recent activity for the last week in the Testnet Leaderboard

### ISSUE THREAD

**Issue by jurlit** [iron-fish/ironfish#972] opened 2022-02-09 07:41 UTC
### What happened?

I don't see any recent activity for the week 11 in the Testnet Leaderboard

We can see common points, but we don't see details. We can see details only for week 10

https://testnet.ironfish.network/users/10390
https://testnet.ironfish.network/users/8566
![Screenshot_2022-02-09-001](https://user-images.githubusercontent.com/28047645/153143947-1851e659-5e4c-45ac-b856-77c8450f876a.png)

**Comment by Kupuyc** [comment] 2022-02-09 10:14
Looks like duplicate of #971

**Comment by jurlit** [comment] 2022-02-09 17:38
I did not see, may be because it closed? But I don't see that problem solved now.

**Comment by leanthebean** [comment] 2022-02-09 17:40
it is indeed a duplicate. It's also a bug with the leaderboard website, not iron fish. already being worked on as part of https://github.com/iron-fish/website-testnet/pull/179

**Closed by leanthebean** 2022-02-09 17:40 UTC
Labels: bug
