### ISSUE TITLE
problems with forks, block heights

### ISSUE THREAD

**Issue by Mayovka** [iron-fish/ironfish#783] opened 2021-12-17 17:33 UTC
I noticed that some servers are mining at the already passed block height, and thus, when mining, they fall into the fork. I think this problem is due to unsuccessful synchronization 
solution problem: sync again
systemctl stop ironfishd-miner ironfishd
rm -r $HOME/.ironfish/databases/
systemctl start ironfishd-miner ironfishd
![Inkedphoto_2021-12-17_19-08-39_LI](https://user-images.githubusercontent.com/95088734/146584896-06a13e00-13c5-44b5-98a8-eb8698e2161b.jpg)

**Comment by gjfrn** [comment] 2021-12-20 00:37
Duplicate of #731

**Comment by leanthebean** [comment] 2022-02-02 08:39
Closing this out in favor of https://github.com/iron-fish/ironfish/issues/731

**Closed by leanthebean** 2022-02-02 08:39 UTC
Labels: testnet-credit
