### ISSUE TITLE
FATAL ERROR Committing semi space failed. Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by QustomQure** [iron-fish/ironfish#1279] opened 2022-05-08 18:58 UTC
### What happened?

Node eat whole memory as i assume.

<--- Last few GCs --->

[11628:0000026992425C50] 97792059 ms: Scavenge 42.2 (49.0) -> 41.2 (49.0) MB, 0.2 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure
[11628:0000026992425C50] 97793231 ms: Scavenge 42.1 (49.0) -> 41.2 (48.0) MB, 0.2 / 0.0 ms  (average mu = 1.000, current mu = 1.000) task
[11628:0000026992425C50] 97794074 ms: Scavenge 42.2 (48.0) -> 41.2 (48.0) MB, 0.3 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure

<--- JS stacktrace --->

FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory
 1: 00007FF6BE60401F
 2: 00007FF6BE593146
 3: 00007FF6BE593FFD
 4: 00007FF6BEEC5ADE
 5: 00007FF6BEEB000D
 6: 00007FF6BED535FC
 7: 00007FF6BED5D31F
 8: 00007FF6BED4FEF9
 9: 00007FF6BED4E0B0
10: 00007FF6BED729E6
11: 00007FF6BEAA5C25
12: 00007FF6BEF534B1
13: 00007FF6BEEE83BE
14: 000002699431CBCD

### Version

0.1.31

### Debug output

```shell
Iron Fish version            0.1.31 @ 4c3b5b9
Iron Fish library            0.0.9 @ 4c3b5b9
Operating system             Windows_NT x64
CPU model(s)                 AMD Ryzen 9 5950X 16-Core Processor
CPU threads                  32
RAM total                    63.92 GiB
Node version                 v16.13.2
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           000000000017aa1446049195dd0e66b2476dc628e266c5b36295e127c6b7728c
Accounts head in chain       true
Accounts head sequence       7023
```

### Graffiti

Qualia

**Comment by lwisne** [comment] 2022-08-03 23:35
Duplicate of https://github.com/iron-fish/ironfish/issues/1925

**Closed by lwisne** 2022-08-03 23:35 UTC
Labels: bug, verified
