### ISSUE TITLE
transactions never show up on blockchain

### ISSUE THREAD

**Issue by msa6867** [iron-fish/ironfish#1490] opened 2022-05-23 19:56 UTC
### Description

On May 13 computer shut off unexpectedly killing both the node and mining processes. The account under which I had been mining was lost from my account list and unusable. I had created the account under name "msa6867"  and had been assigned public key: 0d87e848ff1bb16e7dc10e4aeca517b3e906cef570b3af9a065ab061b63dee19b15c8f5964170be049b889

I restarted IRONFISH node and miner, but all attempts to locate my account were fruitless. accounts:use resulted in error stating account did not exist and accounts:list returned a null set.  I created a new account with the same name and was assigned public key: fcf77bf384221f25ae90583dc62ade76f43b5c5bfb8403b0a636c7f2d663eecab45a3ff2272a1b7c8da665
which I have been using since.  Since that time I have mined using this account and completed ~20 "deposit" transactions.  However none of the transactions ever show up on the blockchain. Please help. A couple transaction logs are pasted below:

C:\Users\mark>ironfish deposit

You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000001 ($ORE 1) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 0.54535282 ($ORE 54,535,282).
The memo will contain the graffiti "msa6867".

* This action is NOT reversible *

Do you confirm (Y/N)?: y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Depositing $IRON 0.10000000 ($ORE 10,000,000) from msa6867
Transaction Hash: c042bc5d240e223ec152b1c70f38a0ab2d8747bbe985798f004483c33657d239
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/c042bc5d240e223ec152b1c70f38a0ab2d8747bbe985798f004483c33657d239 (it can take a few minutes before the transaction appears in the Explorer)

C:\Users\mark>ironfish deposit

You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000001 ($ORE 1) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 0.31438216 ($ORE 31,438,216).
The memo will contain the graffiti "msa6867".

* This action is NOT reversible *

Do you confirm (Y/N)?: y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Depositing $IRON 0.10000000 ($ORE 10,000,000) from msa6867
Transaction Hash: f84832beed74f6ef9a0a4f91726c236c85c96cf1d7e3ac65a6a3d8445d52a7d2
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/f84832beed74f6ef9a0a4f91726c236c85c96cf1d7e3ac65a6a3d8445d52a7d2 (it can take a few minutes before the transaction appears in the Explorer)

**Comment by lwisne** [comment] 2022-08-01 20:21
It is possible the transactions expired. You can help prevent this by adding a larger fee on the transaction (doesn't have to be much larger, like 20 $ORE). 

Is your balance still intact? That would be what happens if the transactions never were fully processed.

**Comment by hughy** [comment] 2022-12-08 20:07
It looks like you were able to get transactions confirmed based on some later issues (e.g., #1640 ). Closing this issue as resolved.

**Closed by hughy** 2022-12-08 20:07 UTC
Labels: bug, needs verification
