### ISSUE TITLE
#bug Error: Failed to iterate between blocks on diverging forks: curr: 00000...4eaa4, end: 00000...ada80, progress: 63004/63003

### ISSUE THREAD

**Issue by WhiL4ent** [iron-fish/ironfish#889] opened 2022-01-13 18:13 UTC
I'm running a node in ubuntu 20.04 It was running well ( graffiti : While4ent I was nb 57 in the leaderboard and now 83) but since the new release i can't get it running.

I updated my node to v0.1.18 and then when I start my node it finish syncing and then after some block I get this error : 

`` /root/ironfish/ironfish/build/src/blockchain/blockchain.js:286
            throw new Error('Failed to iterate between blocks on diverging forks:' +
                  ^

Error: Failed to iterate between blocks on diverging forks: curr: 00000...4eaa4, end: 00a80, progress: 63004/63003
    at Blockchain.iterateToHashes (/root/ironfish/ironfish/build/src/blockchain/blockcha6:19)
    at iterateToHashes.next (<anonymous>)
    at Blockchain.iterateTo (/root/ironfish/ironfish/build/src/blockchain/blockchain.js:
    at iterateTo.next (<anonymous>)
    at Blockchain.iterateAllTransactions (/root/ironfish/ironfish/build/src/blockchain/bn.js:733:26)
    at async Accounts.scanTransactions (/root/ironfish/ironfish/build/src/account/accoun3:80)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``

the line ``Error: Failed to iterate between blocks on diverging forks: curr: 00000...4eaa4, end: 00a80, progress: 63004/63003`` is not fix, the blocks number change but the rest is always the same

**Comment by NullSoldier** [comment] 2022-01-25 22:40
This is a duplicate of https://github.com/iron-fish/ironfish/issues/880 let's track it there

**Closed by NullSoldier** 2022-01-25 22:40 UTC
