### ISSUE TITLE
syn error

### ISSUE THREAD

**Issue by kakathy** [iron-fish/ironfish#1661] opened 2022-06-22 03:44 UTC
### Description

/home/leon/.npm-global/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:190
        err = new ReadError(err)
              ^
Error [ReadError]: Corruption: bad entry in block
    at /home/leon/.npm-global/lib/node_modules/ironfish/node_modules/levelup/lib/levelup.js:190:15 {
  [cause]: undefined
}

**Comment by lwisne** [comment] 2022-08-03 21:35
duplicate of https://github.com/iron-fish/ironfish/issues/1662

**Closed by lwisne** 2022-08-03 21:35 UTC
Labels: bug
