### ISSUE TITLE
BigInt serialization causes node to crash

### ISSUE THREAD

**Issue by maxovitsj** [iron-fish/ironfish#539] opened 2021-12-03 00:16 UTC
Was just happily mining away and got the following error:

this is output from: `journalctl -u ironfishd`
yarn version: 1.22.17
ironfish version: 0.1.7 @ src

```
Dec 02 22:55:29 ironfisher yarn[1218]: Added block to fork seq: 6200, head-seq: 6200, hash: 00000...7c207, head-hash: 00000...1e50c, work: 101287489609434, head-work: 101287489609434, work-diff: 0
Dec 02 22:55:29 ironfisher yarn[1218]: Added block seq: 6200, hash: 00000...7c207, txs: 2, progress: 100.00%, time: 103.7ms
Dec 02 23:19:01 ironfisher yarn[1218]: Added block seq: 6220, hash: 00000...45f5c, txs: 4, progress: 100.00%, time: 1387.3ms
Dec 02 23:23:19 ironfisher yarn[1218]: /root/ironfish/node_modules/js-message/Message.js:38
Dec 02 23:23:19 ironfisher yarn[1218]:         return JSON.stringify(
Dec 02 23:23:19 ironfisher yarn[1218]:                     ^
Dec 02 23:23:19 ironfisher yarn[1218]: TypeError: Do not know how to serialize a BigInt
Dec 02 23:23:19 ironfisher yarn[1218]:     at JSON.stringify (<anonymous>)
Dec 02 23:23:19 ironfisher yarn[1218]:     at Message.getJSON [as JSON] (/root/ironfish/node_modules/js-message/Message.js:38:21)
Dec 02 23:23:19 ironfisher yarn[1218]:     at Parser.format (/root/ironfish/node_modules/node-ipc/entities/EventParser.js:21:21)
Dec 02 23:23:19 ironfisher yarn[1218]:     at Server.emit (/root/ironfish/node_modules/node-ipc/dao/socketServer.js:79:29)
Dec 02 23:23:19 ironfisher yarn[1218]:     at IpcAdapter.emitStream (/root/ironfish/ironfish/build/src/rpc/adapters/ipcAdapter.js:206:21)
Dec 02 23:23:19 ironfisher yarn[1218]:     at Request.onStream (/root/ironfish/ironfish/build/src/rpc/adapters/ipcAdapter.js:180:18)
Dec 02 23:23:19 ironfisher yarn[1218]:     at Request.stream (/root/ironfish/ironfish/build/src/rpc/request.js:41:14)
Dec 02 23:23:19 ironfisher yarn[1218]:     at InterceptReporter.callback (/root/ironfish/ironfish/build/src/rpc/routes/node/getLogStream.js:41:17)
Dec 02 23:23:19 ironfisher yarn[1218]:     at InterceptReporter.log (/root/ironfish/ironfish/build/src/logger/reporters/intercept.js:12:14)
Dec 02 23:23:19 ironfisher yarn[1218]:     at _log (/root/ironfish/node_modules/consola/dist/consola.js:1:7915)
Dec 02 23:23:19 ironfisher yarn[1167]: error Command failed with exit code 1.
Dec 02 23:23:19 ironfisher yarn[1167]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Dec 02 23:48:47 ironfisher systemd[1]: Stopping IronFish Node...
Dec 02 23:48:47 ironfisher systemd[1]: ironfishd.service: Main process exited, code=exited, status=1/FAILURE
Dec 02 23:48:47 ironfisher systemd[1]: ironfishd.service: Failed with result 'exit-code'.
Dec 02 23:48:47 ironfisher systemd[1]: Stopped IronFish Node.

```

**Comment by adasari** [comment] 2021-12-03 00:27
Encountered same error at different block height.

I have made the accounts pay transaction from one account to other. Was playing with `ironfish` commands and node crashed. Not sure exactly what caused the issue. 

```
Dec 02 21:03:17 sound yarn[131879]: Added block seq: 6080, hash: 00000...379fa, txs: 1, progress: 100.00%, time: 30.6ms
Dec 02 21:15:47 sound yarn[131879]: Added block seq: 6100, hash: 00000...ae309, txs: 1, progress: 100.00%, time: 33.5ms
Dec 02 21:38:29 sound yarn[131879]: Added block seq: 6120, hash: 00000...5123b, txs: 1, progress: 100.00%, time: 42.8ms
Dec 02 21:57:23 sound yarn[131879]: Added block seq: 6140, hash: 00000...25c35, txs: 2, progress: 100.00%, time: 528.8ms
Dec 02 22:12:55 sound yarn[131879]: Added block seq: 6160, hash: 00000...e729d, txs: 2, progress: 100.00%, time: 555.1ms
Dec 02 22:16:10 sound yarn[131879]: /root/ironfish/node_modules/js-message/Message.js:38
Dec 02 22:16:10 sound yarn[131879]:         return JSON.stringify(
Dec 02 22:16:10 sound yarn[131879]:                     ^
Dec 02 22:16:10 sound yarn[131879]: TypeError: Do not know how to serialize a BigInt
Dec 02 22:16:10 sound yarn[131879]:     at JSON.stringify (<anonymous>)
Dec 02 22:16:10 sound yarn[131879]:     at Message.getJSON [as JSON] (/root/ironfish/node_modules/js-message/Message.js:38:21)
Dec 02 22:16:10 sound yarn[131879]:     at Parser.format (/root/ironfish/node_modules/node-ipc/entities/EventParser.js:21:21)
Dec 02 22:16:10 sound yarn[131879]:     at Server.emit (/root/ironfish/node_modules/node-ipc/dao/socketServer.js:79:29)
Dec 02 22:16:10 sound yarn[131879]:     at IpcAdapter.emitStream (/root/ironfish/ironfish/build/src/rpc/adapters/ipcAdapter.js:206:21)
Dec 02 22:16:10 sound yarn[131879]:     at Request.onStream (/root/ironfish/ironfish/build/src/rpc/adapters/ipcAdapter.js:180:18)
Dec 02 22:16:10 sound yarn[131879]:     at Request.stream (/root/ironfish/ironfish/build/src/rpc/request.js:41:14)
Dec 02 22:16:10 sound yarn[131879]:     at InterceptReporter.callback (/root/ironfish/ironfish/build/src/rpc/routes/node/getLogStream.js:41:17)
Dec 02 22:16:10 sound yarn[131879]:     at InterceptReporter.log (/root/ironfish/ironfish/build/src/logger/reporters/intercept.js:12:14)
Dec 02 22:16:10 sound yarn[131879]:     at _log (/root/ironfish/node_modules/consola/dist/consola.js:1:7915)
Dec 02 22:16:34 sound yarn[131842]: error Command failed with exit code 1.
Dec 02 22:16:34 sound yarn[131842]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Dec 02 22:51:23 sound systemd[1]: Stopping IronFish Node...
Dec 02 22:51:30 sound systemd[1]: ironfishd.service: Main process exited, code=exited, status=1/FAILURE
Dec 02 22:51:30 sound systemd[1]: ironfishd.service: Failed with result 'exit-code'.
Dec 02 22:51:30 sound systemd[1]: Stopped IronFish Node.
Dec 02 23:00:04 sound systemd[1]: Started IronFish Node.
Dec 02 23:00:04 sound yarn[302606]: yarn run v1.22.17
Dec 02 23:00:04 sound yarn[302606]: $ node start start
Dec 02 23:00:05 sound yarn[302662]: [53B blob data]
Dec 02 23:00:05 sound yarn[302662]: 11:00:05 PM - Found 0 errors. Watching for file changes.
Dec 02 23:00:06 sound yarn[302711]: $ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run start
```

**Comment by dguenther** [comment] 2021-12-03 01:05
Closing as duplicate of #507.

**Closed by dguenther** 2021-12-03 01:05 UTC
