### ISSUE TITLE
[Bug] Import account prompts twice

### ISSUE THREAD

**Issue by CumpsD** [iron-fish/ironfish#733] opened 2021-12-13 13:18 UTC
![image](https://user-images.githubusercontent.com/1201644/145819523-86dfd5e4-ff62-447c-a461-76763d283ec7.png)

When interactively importing an account, the prompts are displayed twice:

```
Enter the account name: cumpsd
Enter the account spending key: xxx
Enter the account incoming view key: Enter the account incoming view key: xxx
Enter the account outgoing view key: Enter the account outgoing view key: xxx
Enter the account public address: Enter the account public address: xxx
Account cumpsd imported.
Run "ironfish accounts:use cumpsd" to set the account as default
```

**Comment by dguenther** [comment] 2021-12-18 02:37
Duplicate of #578

**Closed by dguenther** 2021-12-18 02:37 UTC
