### ISSUE TITLE
Error: libdatachannel error while creating datachannel: Failed to gather local ICE candidates

### ISSUE THREAD

**Issue by guilhermeysm** [iron-fish/ironfish#2482] opened 2022-11-01 17:58 UTC
### What happened?

error while syncing.

Requesting 20 blocks starting at 00000...1fe2c (101204) from ofeB6Mm (usaman)
C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\connections\webRtcConnection.js:133
            this.initializeDataChannel(this.peer.createDataChannel(''));
                                                 ^

Error: libdatachannel error while creating datachannel: Failed to gather local ICE candidates
    at PeerConnection.createDataChannel (<anonymous>)
    at new WebRtcConnection (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\connections\webRtcConnection.js:133:50)
    at PeerManager.initWebRtcConnection (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\peerManager.js:190:28)
    at PeerManager.connectToWebRTC (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\peerManager.js:145:18)
    at PeerConnectionManager.connectToEligiblePeers (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\peerConnectionManager.js:77:38)
    at PeerConnectionManager.eventLoop (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\peerConnectionManager.js:56:22)
    at Timeout._onTimeout (C:\Users\guilh\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\network\peers\peerConnectionManager.js:72:53)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

### Version

v0.1.49

### Debug output

```shell
Iron Fish version                  0.1.49 @ ec57ed3
Iron Fish library                  0.0.26 @ ec57ed3
Operating system                   Windows_NT x64
CPU model(s)                       Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
CPU threads                        8
RAM total                          7.87 GiB
Heap total                         2.01 GiB
Node version                       v16.18.0
ironfish in PATH                   true
Garbage Collector Exposed          false
Telemetry enabled                  false
Node name
Block graffiti                     guilhermeysm
Account a46ce6 uuid                a46ce653-f929-4e1b-890d-f4807f56ca47
Account a46ce6 name                guilhermeysm
Account a46ce6 head hash           000000000002fb4fb3df7d9fc1e5e3ce48e9f6f7cbe09dbd5cbe0aefb60fae15
Account a46ce6 head in chain       true
Account a46ce6 sequence            101201
```

### Relevant log output

```shell
2022/10/31-15:43:35.026 168c Recovering log #722270
2022/10/31-15:43:35.203 168c Delete type=0 #722270
2022/10/31-15:43:35.203 168c Delete type=3 #722268
```

### Graffiti

guilhermeysm

**Comment by NullSoldier** [comment] 2022-11-01 20:07
This is a duplicate of this ticket https://github.com/iron-fish/ironfish/issues/550

**Closed by NullSoldier** 2022-11-01 20:07 UTC
Labels: bug
