### ISSUE TITLE
Node points bug

### ISSUE THREAD

**Issue by alterkahn** [iron-fish/ironfish#1672] opened 2022-06-24 16:23 UTC
### What happened?

The points are not being credited accurately, despite my node is up to date and running.

<img width="1306" alt="Снимок экрана 2022-06-24 в 19 07 12" src="https://user-images.githubusercontent.com/67752860/175575268-8c7815c5-7c20-4e4b-acd0-1d0e7d936b83.png">

<img width="767" alt="Снимок экрана 2022-06-24 в 19 19 40" src="https://user-images.githubusercontent.com/67752860/175576408-90431d6a-19fe-449a-907b-89f9b54b2ae6.png">

<img width="855" alt="Снимок экрана 2022-06-24 в 19 22 10" src="https://user-images.githubusercontent.com/67752860/175576771-87522958-676b-4e3b-b1ce-25429a07431e.png">

### Version

 0.1.36

### Graffiti

alterkahn

**Comment by lwisne** [comment] 2022-08-03 21:28
Same time period as https://github.com/iron-fish/ironfish/issues/1847

Looks like this may be a widespread issue.

**Comment by lwisne** [comment] 2022-08-03 21:29
Duplicate of https://github.com/iron-fish/ironfish/issues/1847

**Closed by lwisne** 2022-08-03 21:29 UTC
Labels: bug, verified
