### ISSUE TITLE
Chain repair - JavaScript heap out of memory

### ISSUE THREAD

**Issue by ksweidmann** [iron-fish/ironfish#1470] opened 2022-05-20 18:42 UTC
### What happened?

i'm run chain:repair --force in server with 64gb ram

### Debug output

```shell
Iron Fish version            0.1.35 @ src
Iron Fish library            0.0.13 @ src
Operating system             Linux x64
CPU model(s)                 AMD Ryzen 9 5950X 16-Core Processor
CPU threads                  32
RAM total                    62.56 GiB
Node version                 v16.8.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           000000000003acb945cb80c0e11fb08b94feb7341c76a80feb5a0047e7d933e1
Accounts head in chain       true
Accounts head sequence       14083
```

### Relevant log output

```shell
ronfish chain:repair --force
Opening node... done.

⚠️ If you start repairing your database, you MUST finish the
process or your database will be in a corrupt state. Repairing
may take 5m 35s or longer.

Are you SURE? (y)es / (n)o: y
Clearing hash to next hash table... done
Clearing Sequence to hash table... done
Repairing head chain tables: [========================================] 14085/14085 100% 0/sec | N/A

Repairing MerkleTrees
Clearing notes MerkleTree... ⣽

<--- Last few GCs --->

[9020:0x55bef2b9e320]    60018 ms: Scavenge 4039.7 (4127.0) -> 4031.7 (4128.8) MB, 16.4 / 0.0 ms  (average mu = 0.292, current mu = 0.180) task 
[9020:0x55bef2b9e320]    62870 ms: Mark-sweep 4042.1 (4128.8) -> 4033.5 (4133.5) MB, 2833.5 / 0.0 ms  (average mu = 0.197, current mu = 0.085) task scavenge might not succeed
[9020:0x55bef2b9e320]    65861 ms: Mark-sweep 4046.4 (4133.5) -> 4036.1 (4135.8) MB, 2946.3 / 0.0 ms  (average mu = 0.111, current mu = 0.015) task scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x55beefaccff4 node::Abort() [node]
 2: 0x55beef984ef2 node::OnFatalError(char const*, char const*) [node]
 3: 0x55beefcc9a1a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0x55beefcc9ca6 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0x55beefe7b4a9  [node]
 6: 0x55beefe7b5ec  [node]
 7: 0x55beefe93b17 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0x55beefe94384 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0x55beefef209c v8::internal::ScavengeJob::Task::RunInternal() [node]
10: 0x55beefd9ed10 non-virtual thunk to v8::internal::CancelableTask::Run() [node]
11: 0x55beefb4af35 node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) [node]
12: 0x55beefb4ccb8 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [node]
13: 0x55bef04cd40e  [node]
14: 0x55bef04df294  [node]
15: 0x55bef04cdbe8 uv_run [node]
16: 0x55beef9ff2ad node::SpinEventLoop(node::Environment*) [node]
17: 0x55beefb1d194 node::NodeMainInstance::Run(int*, node::Environment*) [node]
18: 0x55beefb1d780 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [node]
19: 0x55beefa8efa5 node::Start(int, char**) [node]
20: 0x7f33c9d30ca3 __libc_start_main [/lib64/libc.so.6]
21: 0x55beef9fcf3e _start [node]
/usr/bin/ironfish: line 45:  9020 Aborted                 (core dumped) "$NODE" "$DIR/run" "$@"
```

### Graffiti

ishosting.com

**Comment by lwisne** [comment] 2022-08-03 23:37
Duplicate of https://github.com/iron-fish/ironfish/issues/1925

**Closed by lwisne** 2022-08-03 23:37 UTC
Labels: bug, verified
