### ISSUE TITLE
[0.1.24] Node has stopped unexpectedly: Failed to unwrap shared reference of `NativeTransactionPosted` type from napi value.

### ISSUE THREAD

**Issue by onecooler** [iron-fish/ironfish#1060] opened 2022-02-23 12:03 UTC
### What happened?

No steps to reproduce. Node was found stopped with the following trace in journal:

> Feb 20 22:00:22 localhost.localdomain yarn[380748]: /root/ironfish/ironfish/build/src/primitives/transaction.js:64
Feb 20 22:00:22 localhost.localdomain yarn[380748]:         return this.withReference((t) => t.notesLength());
Feb 20 22:00:22 localhost.localdomain yarn[380748]:                                            ^
Feb 20 22:00:22 localhost.localdomain yarn[380748]: Error: Failed to unwrap shared reference of `NativeTransactionPosted` type from napi value
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at /root/ironfish/ironfish/build/src/primitives/transaction.js:64:44
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at Transaction.withReference (/root/ironfish/ironfish/build/src/primitives/transaction.js:45:24)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at Transaction.notesLength (/root/ironfish/ironfish/build/src/primitives/transaction.js:64:21)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at Blockchain.iterateBlockTransactions (/root/ironfish/ironfish/build/src/blockchain/blockchain.js:773:38)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at async /root/ironfish/ironfish/build/src/account/accounts.js:44:74
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at async Promise.all (index 0)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at async Event.emitAsync (/root/ironfish/ironfish/build/src/event.js:64:9)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at async ChainProcessor.add (/root/ironfish/ironfish/build/src/chainProcessor.js:37:9)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at async ChainProcessor.update (/root/ironfish/ironfish/build/src/chainProcessor.js:80:13)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at async Accounts.updateHead (/root/ironfish/ironfish/build/src/account/accounts.js:66:37) {
Feb 20 22:00:22 localhost.localdomain yarn[380748]:   code: 'InvalidArg'
Feb 20 22:00:22 localhost.localdomain yarn[380748]: }
Feb 20 22:00:23 localhost.localdomain yarn[380721]: error Command failed with exit code 1.
Feb 20 22:00:23 localhost.localdomain yarn[380721]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Version

0.1.24

### Relevant log output

```shell
Feb 20 22:00:22 localhost.localdomain yarn[380748]: /root/ironfish/ironfish/build/src/primitives/transaction.js:64
Feb 20 22:00:22 localhost.localdomain yarn[380748]:         return this.withReference((t) => t.notesLength());
Feb 20 22:00:22 localhost.localdomain yarn[380748]:                                            ^
Feb 20 22:00:22 localhost.localdomain yarn[380748]: Error: Failed to unwrap shared reference of `NativeTransactionPosted` type from napi value
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at /root/ironfish/ironfish/build/src/primitives/transaction.js:64:44
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at Transaction.withReference (/root/ironfish/ironfish/build/src/primitives/transaction.js:45:24)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at Transaction.notesLength (/root/ironfish/ironfish/build/src/primitives/transaction.js:64:21)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at Blockchain.iterateBlockTransactions (/root/ironfish/ironfish/build/src/blockchain/blockchain.js:773:38)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at async /root/ironfish/ironfish/build/src/account/accounts.js:44:74
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at async Promise.all (index 0)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at async Event.emitAsync (/root/ironfish/ironfish/build/src/event.js:64:9)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at async ChainProcessor.add (/root/ironfish/ironfish/build/src/chainProcessor.js:37:9)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at async ChainProcessor.update (/root/ironfish/ironfish/build/src/chainProcessor.js:80:13)
Feb 20 22:00:22 localhost.localdomain yarn[380748]:     at async Accounts.updateHead (/root/ironfish/ironfish/build/src/account/accounts.js:66:37) {
Feb 20 22:00:22 localhost.localdomain yarn[380748]:   code: 'InvalidArg'
Feb 20 22:00:22 localhost.localdomain yarn[380748]: }
Feb 20 22:00:23 localhost.localdomain yarn[380721]: error Command failed with exit code 1.
Feb 20 22:00:23 localhost.localdomain yarn[380721]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Kupuyc** [comment] 2022-02-23 13:10
Duplicate of #1022

**Closed** 2022-02-23 14:41 UTC
Labels: bug
