### ISSUE TITLE
Unable to Send Transaction

### ISSUE THREAD

**Issue by airj1012** [iron-fish/ironfish#2522] opened 2022-11-07 18:38 UTC
### What happened?

Node is telling me that I can't send a transaction because I don't have enough funds. Which is not correct. Sufficient funds have been confirmed by the node as you can see in the screen shot.
![Send Transaction](https://user-images.githubusercontent.com/64874325/200388611-6cc66693-e3a0-4aec-b08d-882612dd22fb.png)

### Version

0.1.51

### Graffiti

airj1012

**Comment by hughy** [comment] 2022-11-10 23:26
@airj1012 are you still seeing this issue?

Could you share output to the following?

- `ironfish status`
- `ironfish accounts:status`
- `ironfish accounts:balance --explain`

Also, could you tell me whether you're running more than one node?

Thanks for your help debugging!

**Comment by hughy** [comment] 2022-11-16 00:47
Thanks for the update!

This can happen if an account is syncing or rescanning: the balance shows an amount from some point earlier in the chain, but the notes in your balance may have been spent at a block that your account hasn't scanned yet.

I'm looking into this issue to see if there are other possible issues!

**Comment by airj1012** [comment] 2022-11-16 13:39
Got the accounts synced up. It kind of worked, but not without what I would call issues.

With the accounts synced, and I hadn't attempted in a transaction in a LONG time, it showed my initial balance of $64 IRON. That transaction didn't go through. On a second attempt, it showed that I had $19 IRON. That transaction went through. However it said I have $30 IRON in Pending. $19 + $30 != $64. Also I don't believe that I should have any in Pending as I haven't been able to send anything recently. It seems stuck.


![2022 11 16 - Ironfish Error](https://user-images.githubusercontent.com/64874325/202195482-7b815194-b430-4ec5-a7e5-0dc32d6cb2e3.png)
![2022 11 16 - Ironfish Error v2](https://user-images.githubusercontent.com/64874325/202195492-a259c2f5-66aa-453c-aa26-be96796ccb1b.png)

**Comment by airj1012** [comment] 2022-11-16 13:46
The only thing that is showing pending, is the transaction that went through and I see on the explorer. And the values are different.
![2022 11 16 - Ironfish Error v3](https://user-images.githubusercontent.com/64874325/202197137-92ee62e6-4e5b-48e0-a339-bbbbecf0c8d5.png)

**Comment by hughy** [comment] 2022-11-16 16:12
All of the screenshots that you've posted have showed at least one pending note worth $IRON 11.18321974. This note seems to be incorrectly marked as pending in your wallet database. 

> it showed my initial balance of $64 IRON. That transaction didn't go through. On a second attempt, it showed that I had $19 IRON. 

In this case, your balance showed $64 IRON, but some of the notes that were marked as unspent had been spent on chain, so your actual balance was lower. There have been issues in the past with notes incorrectly marked as unspent after transactions were added on forks that may have caused this.

> And the values are different.

Which values are different? Is this a transaction that you're sending to the same account as the one sending it?
19.41766727 - (19.41 + 0.00000476) + 11.18321974 = 11.19088225, so the values seem to balance.


We're working on getting out an `accounts:repair` command later this week that could fix the stuck note, but you can also use `accounts:rescan --reset` to fix the database.

**Comment by airj1012** [comment] 2022-11-16 16:15
Although I received a confirmation that transaction went through (with the URL to the explorer), it's show the full about in my balance now. Although I'm synced up.

The problem with accounts:rescan --reset is that it can take 1-2 days. Not really a great work around, from a user perspective. Completely understand y'all are working really hard and most of this stuff is over my head. Just giving you my perspective. All these resets and trying to deposit before the end of Phase 2 makes it really difficult. Wish Phase 2 would come to an end once most of these issues are ironed out. But I guess y'all have a different opinion/plan.

Thanks for your time.

![2022 11 16 - Ironfish Error v15](https://user-images.githubusercontent.com/64874325/202233834-833dc40a-8246-4fe7-80cd-4a831460a141.png)

**Comment by hughy** [comment] 2022-11-16 16:27
It looks like the transaction was mined on a block, but on a fork: https://explorer.ironfish.network/transaction/98cdd130e518b6b2d254e2c530c044e8ff393291545359a3929562f24dc08188

It may have expired before being included on the main chain, which is why the balance was returned to your account.

We know that there have been frustrating issues making deposits, but we're trying to be careful to end Phase 2 in a way that is as fair as possible to everyone who has participated.

**Comment by hughy** [comment] 2022-11-16 20:14
#2595 addresses the root cause of this issue: an expired transaction was synced to the account and added to the balance by mistake.

**Comment by hughy** [comment] 2022-11-21 20:45
@airj1012 , the `accounts:repair` command should resolve the notes tuck in pending state

**Closed** 2022-12-08 22:18 UTC
Labels: bug, verified
