### ISSUE TITLE
No Block found

### ISSUE THREAD

**Issue by hairtail** [iron-fish/ironfish#2142] opened 2022-08-30 12:45 UTC
### What happened?

GetBlockInfo Request over tcp got error:
"No block found with sequence"

### Version

0.1.44 @ src

### Graffiti

miningKing

**Comment by hughy** [comment] 2022-09-13 17:17
@hairtail can you provide the context for this issue so that we can reproduce? What CLI command(s) did you run before seeing this? What was the status of your node?

**Comment by hairtail** [comment] 2022-09-13 23:50
> @hairtail can you provide the context for this issue so that we can reproduce? What CLI command(s) did you run before seeing this? What was the status of your node?

This is response for rpc request getBlockInfo over tcp.

**Comment by hughy** [comment] 2022-09-14 14:13
This is the expected behavior when searching for a block that's not in the chain. If I run `ironfish blocks:show 1000000` I receive the response `No block found with sequence 1000000`.

**Comment by hairtail** [comment] 2022-09-14 15:31
> This is the expected behavior when searching for a block that's not in the chain. If I run `ironfish blocks:show 1000000` I receive the response `No block found with sequence 1000000`.

Yeah. But i got this response when i request getBlockInfo of a confirmed block. I'm sure that is a valid chain sequence. That's  why I open this issue.

**Comment by hughy** [comment] 2022-09-14 15:37
Can you share what you ran to produce the issue? There is not enough information here to reproduce it.

**Comment by hairtail** [comment] 2022-09-14 15:41
> Can you share what you ran to produce the issue? There is not enough information here to reproduce it.

Yeah, I know that. But this is actually hard to reproduce it. Got "no block found" for my first request while got the expected one for my second request, which is 10 mins later from the first one.

**Comment by hughy** [comment] 2022-09-21 23:41
When you were searching for blocks and seeing "No block found" were you searching for recent blocks or blocks that are far back on the chain?

This might happen if your chain were re-organizing from a fork when you first searched.

Has this problem continued? How often does it happen?

**Comment by holahula** [comment] 2023-04-20 22:31
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue

**Closed by holahula** 2023-04-20 22:31 UTC
Labels: bug
