### ISSUE TITLE
[issue name]Transaction abnormal balance is not correct

### ISSUE THREAD

**Issue by 1613557499** [iron-fish/ironfish#1318] opened 2022-05-11 13:12 UTC
### What happened?

A bug happened!
![image](https://user-images.githubusercontent.com/86406225/167858009-48e10ccf-42dd-4371-b9d7-be62e63c31e4.png)

**Comment by deekerno** [comment] 2022-05-11 13:16
This is due to how notes are consumed for transactions on the node. When creating a transaction, notes are used as inputs to furnish the desired transaction amount plus the fee. You will receive your change in the form of output notes which are then stored in your wallet, but only after your transaction has been confirmed by the network and included in a block. The balance during your transaction is the sum of all of the unconsumed notes; the balance after your transaction has been confirmed includes the aforementioned balance plus the output notes (if any) of said transaction.

That being said, there is potential for improving the wording regarding balances, and we'll look into that.

**Comment by lwisne** [comment] 2022-07-26 21:17
We believe this is now fixed. Let us know if you don't agree!

**Closed by lwisne** 2022-07-26 21:17 UTC
Labels: bug
