### ISSUE TITLE
Added block to fork again

### ISSUE THREAD

**Issue by webdevandseo** [iron-fish/ironfish#791] opened 2021-12-18 23:56 UTC
ironfish          | Added block to fork seq: 26638, head-seq: 28427, hash: 00000...6c955, head-hash: 00000...b1aca, work: 1538017018161821, head-work: 1978896784347500, work-diff: 440879766185679
ironfish          | Added block to fork seq: 28431, head-seq: 28431, hash: 00000...2134f, head-hash: 00000...13872, work: 1979357548253039, head-work: 1979357604587820, work-diff: 56334781
ironfish          | Reorganizing chain from 00000...ae1b7 (28433) for 00000...f258b (28433) on prev 00000...94eca (28432)
ironfish          | Reorganized chain. blocks: 1, old: 00000...ae1b7 (28433), new: 00000...94eca (28432), fork: 00000...94eca (28432)
ironfish          | Added block to fork seq: 26639, head-seq: 28433, hash: 00000...88821, head-hash: 00000...f258b, work: 1538017580392071, head-work: 1979587507683390, work-diff: 441569927291319
ironfish          | Added block to fork seq: 26640, head-seq: 28433, hash: 00000...9c3ba, head-hash: 00000...f258b, work: 1538018143994951, head-work: 1979587507683390, work-diff: 441569363688439
ironfish          | Added block seq: 26640, hash: 00000...9c3ba, txs: 1, progress: 100.00%, time: 10.0ms
ironfish          | Added block to fork seq: 28435, head-seq: 28435, hash: 00000...ebb12, head-hash: 00000...86709, work: 1979815282903367, head-work: 1979815338716946, work-diff: 55813579
ironfish          | Added block seq: 28440, hash: 00000...7ac43, txs: 3, progress: 100.00%, time: 5227.9ms
ironfish          | Added block to fork seq: 28440, head-seq: 28440, hash: 00000...4669d, head-hash: 00000...7ac43, work: 1980383515411885, head-work: 1980383515411885, work-diff: 0

**Comment by gjfrn** [comment] 2021-12-20 00:37
Duplicate of #731

**Comment by leanthebean** [comment] 2022-02-03 01:45
Closing this since https://github.com/iron-fish/ironfish/issues/731 has more detail.

**Closed by leanthebean** 2022-02-03 01:45 UTC
Labels: testnet-credit
