### ISSUE TITLE
Errors in the node log

### ISSUE THREAD

**Issue by Rtx-go** [iron-fish/ironfish#867] opened 2022-01-10 19:25 UTC
Errors in the node log
![image](https://user-images.githubusercontent.com/94867506/148826513-5de2d2a8-bb08-4cb2-aca6-47dae803c095.png)

```
Jan 10 19:16:39 server yarn[156779]: Peer 6ONc6cn sent orphan 00000...eb5f5 (58200), syncing orphan chain.
Jan 10 19:16:39 server yarn[156779]: Error when adding new block 58200 from 6ONc6cn: Error: Expected value not to be null
Jan 10 19:16:39 server yarn[156779]:     at Function.isNotNull (/root/ironfish/ironfish/build/src/assert.js:23:19)
Jan 10 19:16:39 server yarn[156779]:     at Syncer.startSync (/root/ironfish/ironfish/build/src/syncer.js:104:25)
Jan 10 19:16:39 server yarn[156779]:     at Syncer.addBlock (/root/ironfish/ironfish/build/src/syncer.js:284:22)
Jan 10 19:16:39 server yarn[156779]:     at async Syncer.addNewBlock (/root/ironfish/ironfish/build/src/syncer.js:309:34)
Jan 10 19:16:39 server yarn[156779]:     at async PeerNetwork.onNewBlock (/root/ironfish/ironfish/build/src/network/peerNetwork.js:479:20)
Jan 10 19:16:39 server yarn[156779]:     at async hdlr (/root/ironfish/ironfish/build/src/network/peerNetwork.js:254:20)
Jan 10 19:16:39 server yarn[156779]:     at async GossipRouter.handle (/root/ironfish/ironfish/build/src/network/messageRouters/gossip.js:62:24)
Jan 10 19:16:39 server yarn[156779]:     at async PeerNetwork.handleMessage (/root/ironfish/ironfish/build/src/network/peerNetwork.js:371:17)
Jan 10 19:16:39 server yarn[156779]:     at async Promise.all (index 0)
Jan 10 19:16:39 server yarn[156779]:     at async Event.emitAsync (/root/ironfish/ironfish/build/src/event.js:64:9)
Jan 10 19:17:01 server yarn[156779]: Peer rwqUM11 (qwe999) sent orphan 00000...f7f8b (58201), syncing orphan chain.
```

**Comment by Rtx-go** [comment] 2022-01-10 19:34
![image](https://user-images.githubusercontent.com/94867506/148827647-b17b6d0a-54e6-479f-8260-1c0337696318.png)

**Comment by NullSoldier** [comment] 2022-01-10 21:00
Thanks for the report, this is a duplicate of https://github.com/iron-fish/ironfish/issues/712

**Closed** 2022-01-12 23:47 UTC
