### ISSUE TITLE
Hosted Node not being credited

### ISSUE THREAD

**Issue by DroidGirl** [iron-fish/ironfish#1665] opened 2022-06-22 13:43 UTC
### What happened?

Account no longer being credited for hosted node. Last credit was on June 17th.

### Version

v0.1.36

### Debug output

```shell
C:\Windows\system32>ironfish debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.36 @ 6dfc736
Iron Fish library       0.0.14 @ 6dfc736
Operating system        Windows_NT x64
CPU model(s)            AMD Ryzen 9 3900 12-Core Processor
CPU threads             24
RAM total               15.91 GiB
Node version            v16.13.2
ironfish in PATH        true
Telemetry enabled       true
```

### Relevant log output

```shell
C:\Windows\system32>ironfish debug
Iron Fish version            0.1.36 @ 6dfc736
Iron Fish library            0.0.14 @ 6dfc736
Operating system             Windows_NT x64
CPU model(s)                 AMD Ryzen 9 3900 12-Core Processor
CPU threads                  24
RAM total                    15.91 GiB
Node version                 v16.13.2
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           000000000005f33278ab37b341adec350bf359d0e27c9877cee6151059553025
Accounts head in chain       true
Accounts head sequence       61844

Version       0.1.36 @ 6dfc736
Node Name     KirbyCoins
Graffiti      KirbyCoins
Peer Identity 1vKdtFkyVDSaAjQbLV/duV/8LSdJ7uggyFg5xY6MAmc=
Peer Agent    ironfish/0.1.36/6dfc736
Peer Port     9033
Bootstrap     test.bn1.ironfish.network

WebSocket server started at :::9033
Connected to the Iron Fish network
Starting sync from tH/1Dbm (Alyona_IronFish). work: +102833078665069, ours: 61844, theirs: 61848
Finding ancestor using linear search on last 3 blocks starting at 00000...53025 (61844) from peer tH/1Dbm (Alyona_IronFish) at 61848
Found peer tH/1Dbm (Alyona_IronFish) ancestor 00000...53025, syncing from 61844 -> 61848 (4) after 1 requests
Requesting 20 blocks starting at 00000...53025 (61844) from tH/1Dbm (Alyona_IronFish)
Finished syncing 4 blocks from tH/1Dbm (Alyona_IronFish)
```

### Graffiti

KirbyCoins

**Comment by wd021** [comment] 2022-06-24 08:15
it's being credited, there was just a backup in the queue for processing on the API. You'll see points beyond June 17th now. Also, the reason you have many credits for June 17th -> https://github.com/iron-fish/ironfish-api/issues/929

**Comment by peter44-a** [comment] 2022-06-26 18:57
> ### What happened?
> Account no longer being credited for hosted node. Last credit was on June 17th.
> 
> ### Version
> v0.1.36
> 
> ### Debug output
> ```shell
> C:\Windows\system32>ironfish debug
> Database in use, skipping output that requires database.
> Stop the node and run the debug command again to show full output.
> 
> Iron Fish version       0.1.36 @ 6dfc736
> Iron Fish library       0.0.14 @ 6dfc736
> Operating system        Windows_NT x64
> CPU model(s)            AMD Ryzen 9 3900 12-Core Processor
> CPU threads             24
> RAM total               15.91 GiB
> Node version            v16.13.2
> ironfish in PATH        true
> Telemetry enabled       true
> ```
> 
> ### Relevant log output
> ```shell
> C:\Windows\system32>ironfish debug
> Iron Fish version            0.1.36 @ 6dfc736
> Iron Fish library            0.0.14 @ 6dfc736
> Operating system             Windows_NT x64
> CPU model(s)                 AMD Ryzen 9 3900 12-Core Processor
> CPU threads                  24
> RAM total                    15.91 GiB
> Node version                 v16.13.2
> ironfish in PATH             true
> Telemetry enabled            true
> Accounts head hash           000000000005f33278ab37b341adec350bf359d0e27c9877cee6151059553025
> Accounts head in chain       true
> Accounts head sequence       61844
> 
> Version       0.1.36 @ 6dfc736
> Node Name     KirbyCoins
> Graffiti      KirbyCoins
> Peer Identity 1vKdtFkyVDSaAjQbLV/duV/8LSdJ7uggyFg5xY6MAmc=
> Peer Agent    ironfish/0.1.36/6dfc736
> Peer Port     9033
> Bootstrap     test.bn1.ironfish.network
> 
> WebSocket server started at :::9033
> Connected to the Iron Fish network
> Starting sync from tH/1Dbm (Alyona_IronFish). work: +102833078665069, ours: 61844, theirs: 61848
> Finding ancestor using linear search on last 3 blocks starting at 00000...53025 (61844) from peer tH/1Dbm (Alyona_IronFish) at 61848
> Found peer tH/1Dbm (Alyona_IronFish) ancestor 00000...53025, syncing from 61844 -> 61848 (4) after 1 requests
> Requesting 20 blocks starting at 00000...53025 (61844) from tH/1Dbm (Alyona_IronFish)
> Finished syncing 4 blocks from tH/1Dbm (Alyona_IronFish)
> ```
> 
> ### Graffiti
> KirbyCoins



> ### What happened?
> Account no longer being credited for hosted node. Last credit was on June 17th.
> 
> ### Version
> v0.1.36
> 
> ### Debug output
> ```shell
> C:\Windows\system32>ironfish debug
> Database in use, skipping output that requires database.
> Stop the node and run the debug command again to show full output.
> 
> Iron Fish version       0.1.36 @ 6dfc736
> Iron Fish library       0.0.14 @ 6dfc736
> Operating system        Windows_NT x64
> CPU model(s)            AMD Ryzen 9 3900 12-Core Processor
> CPU threads             24
> RAM total               15.91 GiB
> Node version            v16.13.2
> ironfish in PATH        true
> Telemetry enabled       true
> ```
> 
> ### Relevant log output
> ```shell
> C:\Windows\system32>ironfish debug
> Iron Fish version            0.1.36 @ 6dfc736
> Iron Fish library            0.0.14 @ 6dfc736
> Operating system             Windows_NT x64
> CPU model(s)                 AMD Ryzen 9 3900 12-Core Processor
> CPU threads                  24
> RAM total                    15.91 GiB
> Node version                 v16.13.2
> ironfish in PATH             true
> Telemetry enabled            true
> Accounts head hash           000000000005f33278ab37b341adec350bf359d0e27c9877cee6151059553025
> Accounts head in chain       true
> Accounts head sequence       61844
> 
> Version       0.1.36 @ 6dfc736
> Node Name     KirbyCoins
> Graffiti      KirbyCoins
> Peer Identity 1vKdtFkyVDSaAjQbLV/duV/8LSdJ7uggyFg5xY6MAmc=
> Peer Agent    ironfish/0.1.36/6dfc736
> Peer Port     9033
> Bootstrap     test.bn1.ironfish.network
> 
> WebSocket server started at :::9033
> Connected to the Iron Fish network
> Starting sync from tH/1Dbm (Alyona_IronFish). work: +102833078665069, ours: 61844, theirs: 61848
> Finding ancestor using linear search on last 3 blocks starting at 00000...53025 (61844) from peer tH/1Dbm (Alyona_IronFish) at 61848
> Found peer tH/1Dbm (Alyona_IronFish) ancestor 00000...53025, syncing from 61844 -> 61848 (4) after 1 requests
> Requesting 20 blocks starting at 00000...53025 (61844) from tH/1Dbm (Alyona_IronFish)
> Finished syncing 4 blocks from tH/1Dbm (Alyona_IronFish)

> KirbyCoins



> ### What happened?
> Account no longer being credited for hosted node. Last credit was on June 17th.
> 
> ### Version
> v0.1.36
> 
> ### Debug output
> ```shell
> C:\Windows\system32>ironfish debug
> Database in use, skipping output that requires database.
> Stop the node and run the debug command again to show full output.
> 
> Iron Fish version       0.1.36 @ 6dfc736
> Iron Fish library       0.0.14 @ 6dfc736
> Operating system        Windows_NT x64
> CPU model(s)            AMD Ryzen 9 3900 12-Core Processor
> CPU threads             24
> RAM total               15.91 GiB
> Node version            v16.13.2
> ironfish in PATH        true
> Telemetry enabled       true
> ```
> 
> ### Relevant log output
> ```shell
> C:\Windows\system32>ironfish debug
> Iron Fish version            0.1.36 @ 6dfc736
> Iron Fish library            0.0.14 @ 6dfc736
> Operating system             Windows_NT x64
> CPU model(s)                 AMD Ryzen 9 3900 12-Core Processor
> CPU threads                  24
> RAM total                    15.91 GiB
> Node version                 v16.13.2
> ironfish in PATH             true
> Telemetry enabled            true
> Accounts head hash           000000000005f33278ab37b341adec350bf359d0e27c9877cee6151059553025
> Accounts head in chain       true
> Accounts head sequence       61844
> 
> Version       0.1.36 @ 6dfc736
> Node Name     KirbyCoins
> Graffiti      KirbyCoins
> Peer Identity 1vKdtFkyVDSaAjQbLV/duV/8LSdJ7uggyFg5xY6MAmc=
> Peer Agent    ironfish/0.1.36/6dfc736
> Peer Port     9033
> Bootstrap     test.bn1.ironfish.network
> 
> WebSocket server started at :::9033
> Connected to the Iron Fish network
> Starting sync from tH/1Dbm (Alyona_IronFish). work: +102833078665069, ours: 61844, theirs: 61848
> Finding ancestor using linear search on last 3 blocks starting at 00000...53025 (61844) from peer tH/1Dbm (Alyona_IronFish) at 61848
> Found peer tH/1Dbm (Alyona_IronFish) ancestor 00000...53025, syncing from 61844 -> 61848 (4) after 1 requests
> Requesting 20 blocks starting at 00000...53025 (61844) from tH/1Dbm (Alyona_IronFish)
> Finished syncing 4 blocks from tH/1Dbm (Alyona_IronFish)
> ```
> 
> ### Graffiti
> KirbyCoins

Hey
Has your issue been resolved or would you need help? 
Have you been credited

**Comment by lwisne** [comment] 2022-08-03 21:46
Duplicate of https://github.com/iron-fish/ironfish/issues/1847

This is from a period where it does look like there was a gap in TN points rewarded.

**Closed by lwisne** 2022-08-03 21:46 UTC
Labels: bug, testnet-credit
