### ISSUE TITLE
Didn't get reward!

### ISSUE THREAD

**Issue by cnly39** [iron-fish/ironfish#1435] opened 2022-05-18 04:20 UTC
### What happened?

It seems that website has display error.It shows that '-10 hour until next reward'.

### Version

0.1.34 @ e0f5e11

### Debug output

```shell
Iron Fish version       0.1.34 @ e0f5e11
Iron Fish library       0.0.12 @ e0f5e11
Operating system        Linux x64
CPU model(s)            DO-Premium-Intel
CPU threads             4
RAM total               7.77 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
```

### Relevant log output

```shell
https://drive.google.com/file/d/1G5X228jZu7LMQhR2bYLwChbfRXBlxMPd/view?usp=sharing
```

### Graffiti

pr_ironfish

**Comment by wd021** [comment] 2022-05-26 21:28
duplicate of https://github.com/iron-fish/ironfish/issues/1414

**Closed** 2022-08-01 21:00 UTC
Labels: bug
