### ISSUE TITLE
deposits/payments returned back, most notes finally deposited from 3-5 tries, some cannot at all. it starts since 2022-07-07

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#1749] opened 2022-07-08 13:45 UTC
### What happened?
Deposits returned back.
It start happening yesterday for some deposits (2022-07-07), now (2022-07-08) almost for all, it finally deposited after 3-5 retries only.
Doing fresh test,  fresh node, new empty address (have sent 2.5 iron from main node).
![изображение](https://user-images.githubusercontent.com/13568002/178066808-b2ff072d-796f-4229-991a-b33886f043fc.png)

Here we sent 24 transactions with depositAll (all fine for now):
![изображение](https://user-images.githubusercontent.com/13568002/178066893-d1b28602-d484-4247-97bb-4b3f97051227.png)

Here some of them returned and already resent
![изображение](https://user-images.githubusercontent.com/13568002/178066927-887edbd9-aa43-4d57-829e-98a9eb5c5cd5.png)

Next node was crashed (because of depositAll or deposit with near zero balance - i made this bug report too), doing rescan now, will update later.

Rescan is done, still have some returned.
![изображение](https://user-images.githubusercontent.com/13568002/178094636-1b29217b-5913-4c4e-a62e-e59f11c6111e.png)

trying depositAll again
![изображение](https://user-images.githubusercontent.com/13568002/178094692-43ffa5de-4489-4888-bb2f-cacf16b3adb1.png)

some progress, already some returned and resent
![изображение](https://user-images.githubusercontent.com/13568002/178096343-97946494-df78-4d17-bb5c-fd93a9e91094.png)

the last one cannot send at all, tried about 15 times, last tries on screenshoot
![изображение](https://user-images.githubusercontent.com/13568002/178100379-f93968a3-9243-4cba-bf27-7b53e741e439.png)

Also i have another wallet with 1.1 iron, tried about ~20 times, all returning back.

sending between accounts  (pay) have same trouble too, last 2 days it mostly returning back.

Today (2022-07-09) things getting worse, the test of depositing 10 IRON:
![изображение](https://user-images.githubusercontent.com/13568002/178120908-c1ec4acc-bf48-41f8-8297-3712b258b10e.png)
All are returing back now.

### Version

0.1.37

### Graffiti

ar2Obyahain

**Comment by rohanjadvani** [comment] 2022-07-08 15:50
I'm confused what the bug here is; 2022-07-22 is a date in the future.

**Comment by gzivdo** [comment] 2022-07-08 20:42
> I'm confused what the bug here is; 2022-07-22 is a date in the future.

updated text, date was wrong, sorry, i changed now. just created bug earlier than gathered all info, sorry

**Comment by lwisne** [comment] 2022-08-03 16:55
This is likely due to transactions not being picked up due to too low of fees + a poor UI into expired transactions.

Duplicate of https://github.com/iron-fish/ironfish/issues/1727

See thread there for more info, and the plan to fix.

We are working on this - you will be able to easily send your funds again soon!

**Closed** 2022-08-03 16:55 UTC
Labels: bug
