### ISSUE TITLE
Issues Updating to 1.50

### ISSUE THREAD

**Issue by airj1012** [iron-fish/ironfish#2474] opened 2022-11-01 12:55 UTC
### What happened?

Receiving the attached error when I try to update to ironfish 1.50

![Update Error](https://user-images.githubusercontent.com/64874325/199236410-0cb86ba8-facb-4d3a-ac04-a4342500a143.png)

Confirmed I'm on Nodejs 16.18.0, CMake 3.25.0-rc and Visual Studio 2019

![VS and CMake](https://user-images.githubusercontent.com/64874325/199236683-933b369e-4b98-4ef5-b63b-fe284215c32f.png)

I've tried installing a few different times with no success. After a few failed attempts I continued to use 1.49. However I'm not able to do that anymore either. Something broke there and I can't get the old version to work now either.

![1 49](https://user-images.githubusercontent.com/64874325/199236929-97839835-2f1c-4816-a5bb-404f23f48875.png)

### Version

0.1.49

### Graffiti

airj1012

**Comment by NullSoldier** [comment] 2022-11-01 15:43
This is a duplicate of this existing ticket. https://github.com/iron-fish/ironfish/issues/2473

**Closed by NullSoldier** 2022-11-01 15:43 UTC
Labels: bug

**Comment by airj1012** [comment] 2022-11-01 15:46
Is this a complete duplicate? My 1.49 no longer works now either.
