### ISSUE TITLE
#bug undefined is not a 64-character hex string

### ISSUE THREAD

**Issue by tsonghua** [iron-fish/ironfish#876] opened 2022-01-11 04:40 UTC
Windows Docker  

Graffiti: smart

block 62444. 

Error:  error when adding new block 62444 from N5xNhhV:error: undefined is not a 64-character hex string

Error when adding new block 62447 from fosuUW6 (kdpyatkov): Error: undefined is not a 64-character hex string

    at Uint8ArraySerde.deserialize (/usr/src/app/node_modules/ironfish/build/src/serde/Uint8ArraySerde.js:40:19)

    at BufferSerde.deserialize (/usr/src/app/node_modules/ironfish/build/src/serde/BufferSerde.js:26:39)

    at BlockHeaderSerde.deserialize (/usr/src/app/node_modules/ironfish/build/src/primitives/blockheader.js:156:270)

    at BlockSerde.deserialize (/usr/src/app/node_modules/ironfish/build/src/primitives/block.js:113:50)

    at Syncer.addBlock (/usr/src/app/node_modules/ironfish/build/src/syncer.js:278:54)

    at Syncer.addNewBlock (/usr/src/app/node_modules/ironfish/build/src/syncer.js:309:45)

    at PeerNetwork.onNewBlock (/usr/src/app/node_modules/ironfish/build/src/network/peerNetwork.js:479:43)

    at /usr/src/app/node_modules/ironfish/build/src/network/peerNetwork.js:87:34

    at hdlr (/usr/src/app/node_modules/ironfish/build/src/network/peerNetwork.js:254:26)

    at async GossipRouter.handle (/usr/src/app/node_modules/ironfish/build/src/network/messageRouters/gossip.js:62:24)

![ironfish_bug_011102](https://user-images.githubusercontent.com/3368177/148882306-e6ef80a7-3f96-4fd1-9c38-0a5de96ffe48.png)
![ironfish_bug_011101](https://user-images.githubusercontent.com/3368177/148882314-81afdc0b-53b1-43a3-bdca-5da34c0d3e56.png)

**Comment by QustomQure** [comment] 2022-01-11 05:42
Thank you for your report. It is duplicate of #873

**Comment by deekerno** [comment] 2022-02-03 18:49
Duplicate of #873, which was fixed in v0.1.18.

**Closed by deekerno** 2022-02-03 18:49 UTC
