### ISSUE TITLE
EncodingError: Number exceeds 2^53-1

### ISSUE THREAD

**Issue by mumu714** [iron-fish/ironfish#2495] opened 2022-11-02 03:14 UTC
### What happened?

Node start error
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/99628484/199386931-f8085eb2-a642-41f1-8d47-79337ad034ed.png">

### Version

v0.1.50

### Debug output

```shell
/mnt/md0/ironfish/ironfish/node_modules/bufio/lib/encoding.js:61
  check((hi & 0xffe00000) === 0, off, 'Number exceeds 2^53-1');
  ^

EncodingError: Number exceeds 2^53-1 (offset=0).
    at Object.readU64 (/mnt/md0/ironfish/ironfish/node_modules/bufio/lib/encoding.js:61:3)
    at BufferReader.readU64 (/mnt/md0/ironfish/ironfish/node_modules/bufio/lib/reader.js:364:26)
    at new Transaction (/mnt/md0/ironfish/ironfish/ironfish/build/src/primitives/transaction.js:21:38)
    at TransactionsValueEncoding.deserialize (/mnt/md0/ironfish/ironfish/ironfish/build/src/blockchain/database/transactions.js:24:31)
    at LevelupStore.get (/mnt/md0/ironfish/ironfish/ironfish/build/src/storage/levelup/store.js:43:39)
    at async LevelupTransaction.get (/mnt/md0/ironfish/ironfish/ironfish/build/src/storage/levelup/transaction.js:63:23)
    at async Promise.all (index 1)
    at async /mnt/md0/ironfish/ironfish/ironfish/build/src/blockchain/blockchain.js:511:44
    at async LevelupDatabase.withTransaction (/mnt/md0/ironfish/ironfish/ironfish/build/src/storage/database/database.js:41:28)
    at async Blockchain.iterateBlockTransactions (/mnt/md0/ironfish/ironfish/ironfish/build/src/blockchain/blockchain.js:789:23) {
  type: 'EncodingError',
  code: 'ERR_ENCODING'
}
```

### Graffiti

muyao

**Comment by wd021** [comment] 2022-11-02 06:41
duplicate of https://github.com/iron-fish/ironfish/issues/2061 and https://github.com/iron-fish/ironfish/issues/2471

**Comment by holahula** [comment] 2023-04-20 22:24
Closing - dupe

**Closed by holahula** 2023-04-20 22:24 UTC
Labels: bug
