### ISSUE TITLE
IronFish Status Shows 2 Mined, but Only Mined 1

### ISSUE THREAD

**Issue by temis20** [iron-fish/ironfish#656] opened 2021-12-08 18:56 UTC
In my status container, I see "Mining  STARTED - 1 miners, 2 mined". However, the command 'ironfish miners:mined' only shows 1 mined. My account balance shows 20 IRON, so I am confident that I have only actually mined 1 block. 

I'm thinking that I did mine a block, but it was forked or otherwise not counted in the main chain.

If this is one that qualifies for points, my username for the incentivized testnet is 'zkstorm'.

**Comment by dguenther** [comment] 2021-12-08 19:27
Closing this as a duplicate of #649 , but feel free to still submit this issue for points by filling out the "Claim Points" form under "Finding Bugs" here: https://testnet.ironfish.network/about

**Closed by dguenther** 2021-12-08 19:27 UTC
