### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by linuxhead** [iron-fish/ironfish#1579] opened 2022-06-06 02:43 UTC
### What happened?

运行docker一段时间，自己就停止了，显示内存溢出

### Relevant log output

```shell
<--- Last few GCs --->

[7:0x672e030] 25930519 ms: Mark-sweep (reduce) 4041.9 (4117.2) -> 4009.5 (4090.2) MB, 245.8 / 0.2 ms  (average mu = 0.245, current mu = 0.192) allocation failure GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb02ec0 node::Abort() [node]
 2: 0xa181fb node::FatalError(char const*, char const*) [node]
 3: 0xced88e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
```

### Graffiti

werwaa

**Comment by lwisne** [comment] 2022-08-03 23:40
Duplicate of https://github.com/iron-fish/ironfish/issues/1925

**Closed by lwisne** 2022-08-03 23:40 UTC
Labels: bug, verified
