### ISSUE TITLE
Deposits Lag

### ISSUE THREAD

**Issue by airj1012** [iron-fish/ironfish#2336] opened 2022-10-12 19:35 UTC
### What happened?

Today I've run ironfish deposit-all twice and in both instances, it's taken 5-10 minutes before being prompted with the confirm screen.

Similarly, on my first run, I saw the completed transactions but no updates to the leaderboard. Even after a few hours.

### Version

0.1.49

### Graffiti

airj1012

**Comment by airj1012** [comment] 2022-10-13 00:37
![image](https://user-images.githubusercontent.com/64874325/195472610-17d25284-ef26-4e6e-bc7f-3ba7b3ee5f20.png)

![image](https://user-images.githubusercontent.com/64874325/195472630-e90149b0-7156-416d-b219-9ce5789185ed.png)

![image](https://user-images.githubusercontent.com/64874325/195472644-e4335d63-0c76-454e-bee9-be6af9178aa5.png)

**Comment by hughy** [comment] 2022-10-13 16:22
> Today I've run ironfish deposit-all twice and in both instances, it's taken 5-10 minutes before being prompted with the confirm screen.

When running `deposit-all` are you specifying the transaction fee using the `--fee` flag?

One source of slowness is that when no fee is supplied the command will look at previous blocks to suggest a fee, which can take a long time. We're currently working on improving the performance of fee estimation.

**Comment by airj1012** [comment] 2022-10-15 15:02
I wasn't, no. I think the speed improved, but I have since starting using a fee. However still having lots of issues getting my deposits accepted before the expire.

**Comment by danield9tqh** [comment] 2022-11-02 18:46
Hey @airj1012 we are aware that deposits take a long time to be confirmed. It's most likely network congestion. Since blocks are full it's very competitive to get a confirmed transaction into a block. We're alleviating this by allowing users to deposit more iron in a single transaction and will continue to do this until everyone who wants to get their transactions in for phase 2 is able to. I am going to close this for now since it seems like this is the issue and the fix is in progress. If you are still unable to get deposits in closer to the end of Phase 2 don't hesitate to reach out here or on discord.

**Closed by danield9tqh** 2022-11-02 18:46 UTC
Labels: bug
