### ISSUE TITLE
FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by msa6867** [iron-fish/ironfish#1399] opened 2022-05-14 16:06 UTC
### What happened?

Miner fatally stopped overnight.  Did not affect node which seems to be running fine. No other process running besides miner and node. joined mining pool using command ironfish miners:start -p pool.ironfish.network -a fcf77bf384221f25ae90583dc62ade76f43b5c5bfb8403b0a636c7f2d663eecab45a3ff2272a1b7c8da665 -t 6

error sequence occurred about 3 hours into successul mining

### Version

v0.1.32

### Debug output

```shell
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.32 @ 1abccc9
Iron Fish library       0.0.10 @ 1abccc9
Operating system        Windows_NT x64
CPU model(s)            AMD Ryzen 3 4300G with Radeon Graphics
CPU threads             8
RAM total               7.37 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
```

### Relevant log output

```shell
Found share: 0000000002613dca 13465 19.34 MH/s
Disconnected from pool unexpectedly. Reconnecting.
Successfully connected to pool
Listening to pool for new work
Hashrate... / 0 H/s (0)

<--- Last few GCs --->

[12464:0000024AB5D12F70] 17207242 ms: Scavenge 21.9 (30.5) -> 21.1 (30.5) MB, 1.5 / 0.0 ms  (average mu = 1.000, current mu = 1.000) task
[12464:0000024AB5D12F70] 17212005 ms: Scavenge 21.9 (30.5) -> 21.2 (30.5) MB, 11.7 / 0.0 ms  (average mu = 1.000, current mu = 1.000) task
[12464:0000024AB5D12F70] 17216857 ms: Scavenge 22.0 (30.5) -> 21.3 (30.5) MB, 1.5 / 0.0 ms  (average mu = 1.000, current mu = 1.000) task


<--- JS stacktrace --->

FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory
 1: 00007FF7050C7A1F
 2: 00007FF705056096
 3: 00007FF705056F4D
 4: 00007FF70598B2CE
 5: 00007FF7059758AD
 6: 00007FF705818C7C
 7: 00007FF70582299F
 8: 00007FF705815559
 9: 00007FF7057C5AC5
10: 00007FF704FE796F
11: 00007FF704FE6186
12: 00007FF705126F2B
13: 00007FF7051266BC
14: 00007FF70512685A
15: 00007FF7050F56C5
16: 00007FF70500E853
17: 00007FF70508AADC
18: 00007FF704EA897C
19: 00007FF705F0FE98
20: 00007FFA5E3B54E0
21: 00007FFA5FC8485B
```

### Graffiti

msa6867

**Comment by lwisne** [comment] 2022-08-03 23:36
Duplicate of https://github.com/iron-fish/ironfish/issues/1925

**Closed by lwisne** 2022-08-03 23:36 UTC
Labels: bug, verified
