### ISSUE TITLE
Ironfish 0.1.40 (and 0.1.44) won't fully re-trigger getting work from a mining pool after pool reset until mining client is restarted, causing Subscribe event.

### ISSUE THREAD

**Issue by crProductGuy** [iron-fish/ironfish#1886] opened 2022-07-30 18:27 UTC
### What happened?

2 Windows-based miners were pool-mining OK on peak-pool.com.

Peak-pool had an issue. The pool operator fixed the issue, yet after the pool fix, the ironfish miner processes weren't receiving work from the pool despite continuously requesting work.  The miners were idle and had zero hashrate for several hours on 30july22 while the pool was back up.   See miner logs below.

Workaround:
To start successful mining again both times after a peak-pool mining server restart, I had to ctrl-c out of the `ironfish miners` mining processes and re-start mining.
Each miner then immediately started requesting work **and receiving work**. They showed the expected hashrate and started winning shares. 

The same thing happened a few days ago on 27july after a similar peak-pool problem and pool server restart.  My miners were idle for hours while continously requesting work, even though the pool was back up.

Environment : Windows 11 running `ironfish miners:start` in either CMD or PowerShell
 ironfish installed with npm on an 8-core Ryzen.

Comments:
While in this no-work situation after pool restoration, the mining process appears to request work, but there **must be some stuck state that blocks it from actually receiving work**.   The fact of no connection errors suggest that the pool IP remained constant and reachable.  Only the "send work" or "receive work" part of the interaction didn't happen correctly.

Is that "stuck wrong state" in the ironfish miner, or in the Peak-pool pool-serving code?

There must be a difference between what happens in the miner when it asks for work in a repeat loop, vs. something "stronger" it does when the miner first starts and connects to the remote pool server. 

  What state is reset after restarting & reconnecting, and in which software (iron fish or peak-pool), that is preventing requested work from being delivered from pool to miner?

IMO the Iron Fish miner needs to be more aggressive when it asks for work, especially if it hasn't received work from the pool for an extended period of time (max 5-10 min).  There's an argument to put in some kind of synchronous or async timeout in the ironfish miner code, that forces a full pool reconnect attempt after receiving no new work for a while.

Goal: that would ensure that miners aren't left idle for hours after a pool problem & restart.

When troubleshooting & isolating this, if there is a stuck-state issue discovered on the peak-pool side, let's publish it in iron fish pool-support docs so that any other pool developers and operators know how to "do it right" and avoid the problem in the future.

---

`ironfish debug` Output:

### Version

0.1.40

### Debug output

```shell
Iron Fish version            0.1.40 @ 0918065
Iron Fish library            0.0.18 @ 0918065
Operating system             Windows_NT x64
CPU model(s)                 AMD Ryzen 7 5700G with Radeon Graphics
CPU threads                  16
RAM total                    31.34 GiB
Heap total                   4.02 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash
Accounts head in chain       false
Accounts head sequence       null
```

### Relevant log output

```shell
Miner log:
Disconnected from pool unexpectedly. Reconnecting.
Successfully connected to pool
Subscribing to pool to receive work
Disconnected from pool unexpectedly. Reconnecting.
Successfully connected to pool
Subscribing to pool to receive work
Hashrate... \ 0 H/s (0)    << repeated for hours >>
User input: Ctrl-C
ironfish miners:start -t 16 -p stratum://peak-pool.com:9034 -a d26b6c24...1af9d24350e
Starting to mine with public address: d26b6c2402f826b85d9117e034b5e153f34e95934af2e3764599411bb4a71c67512b7d373491af9d24350e at pool 185.230.163.150:9034
Connecting to pool...
Successfully connected to pool
Subscribing to pool to receive work
Found share: 00000000067382ac 0 31.40 MH/s
Hashrate... / 59.41 MH/s (59418636)
Disconnected from pool unexpectedly. Reconnecting.
Successfully connected to pool
Subscribing to pool to receive work
Disconnected from pool unexpectedly. Reconnecting.
Successfully connected to pool
Subscribing to pool to receive work
Hashrate... \ 0 H/s (0)

( above Hashrate 0 persisted for hours )

User actions:

Ctrl-C

ironfish miners:start -t 16 -p stratum://peak-pool.com:9034 -a d26b6c2402f826b85d9117e034.....764599411bb4a71c67512b7d373491af9d24350e
Starting to mine with public address: d26b6c2402f826.....b4a71c67512b7d373491af9d24350e at pool 185.230.163.150:9034
Connecting to pool...
Successfully connected to pool
Subscribing to pool to receive work
Found share: 00000000067382ac 0 31.40 MH/s
Hashrate... / 59.41 MH/s (59418636)
```

### Graffiti

ProductGuy

**Comment by hamza-siddiq** [comment] 2022-08-01 17:29
Tried to reproduce this but to no avail. This might be an issue on the bug reporter's end.
![IMG-20220801-WA0014](https://user-images.githubusercontent.com/92462002/182207802-3167ec6c-38a3-4706-b838-d941488a2a17.jpg)

**Comment by lwisne** [comment] 2022-08-03 22:06
Agree that mining via pool still has plenty of usability issues. Would love for someone to look at this further.

**Comment by crProductGuy** [comment] 2022-08-26 04:00
Update: on current v0.1.44 this occurred on the official pool on 25aug22, when the pool was giving zero hash and then was restarted, 2 connected pool miner clients received no work and had zero hash until they were stopped and restarted, causing a re-subscribe. Then they got work and had normal hashrate.

I believe that this means that staying connected to the 1st tier of the mining pool is not sufficient to cause a resubscribe after the 2nd or deeper pool tiers are restarted.

The fix would seem to be either enhance the stratum protocol to re-subscribe periodically, or do this at the application layer in the mining client periodically, especially if the miner is not receiving work for more than a couple of minutes or max 5 min.

The preferred fix should be shared with all the known mining pool operators and published in a Mining Pool Developers Guide, so it becomes part of best common practices.  Thanks!

-=-=-=
eve of 24aug PDT

I had to kill and restart pool mining client, which re-subscribes, to get work and hashrate after a pool fix by Ironfish staff.
Same on each of 2 mining machines.

pool mining client log: :

Connecting to pool...
Successfully connected to pool
Subscribing to pool to receive work
Hashrate... - 0 H/s (0)

PS C:\Users\M> **^C**

PS C:\Users\M> ironfish miners:start -t 16 --pool pool.ironfish.network -a d26b6c2402f826...2b7d373491af9d24350e
Starting to mine with public address: d26b6c2402f826...2b7d373491af9d24350e at pool 54.90.34.95:9034
Connecting to pool...
Successfully connected to pool
**Subscribing to pool to receive work**
Hashrate... | 59.34 MH/s (59349327)

-=-=-=-

From the Discord convo between ProductGuy and AdiDev:
24aug22:
ProductGuy reporting pool problem with zero hash:
https://discord.com/channels/771503434028941353/816795916627345450/1012169965970935838
ProductGuy — Yesterday at 6:22 PM
mining pool is in a weird state.  Connects, subscribe OK, 0 hashrate.  Seems new in the last few hours.  Curiously same thing from Peak-pool.  Might be coincidence.  Both of my miners affected.
AdiDev — Yesterday at 6:23 PM
Yes, just saw. The last block submitted from the official pool was about 3.5 hours ago. Thanks for bringing it to our attention! Shall inform the team
ProductGuy — Yesterday at 6:24 PM
great, thanks, Adi

---

Follow-up Thurs 25aug22 from ProductGuy:
https://discord.com/channels/771503434028941353/816795916627345450/1012418926954684476

I believe last night’s mining pool restoration showed another occurrence of https://github.com/iron-fish/ironfish/issues/1886, where you have to stop a pool mining client and restart it, which re-subscribes, in order for the miner to get work has have hashrate.   Whatever restoration of the pool was done did not cause connected miners to start getting work again.  Miners continued after the pool restoration with zero hash.   I don’t know if this is a general weakness in the Stratum protocol, or is Ironfish specific, but I believe an enhancement is needed so that connected miners will automatically start getting work again after a partly-down  pool is restored.  I’m now convinced that an automatic “re-subscribe” should be done periodically by a pool mining client, especially if it is connected has not been receiving work.   This enhancement should (whether in the Stratum protocol or a client application later subscription call addition) should be shared with all the known mining pool operators and added to the “Pool Mining Developer’s Guide” if there is one.    Tonight I will add text I captured from my client last night (connected with zero hash, Ctrl-c by me, restarted miner, got expected hashrate)
What seems to happen now is that the mining client is connected to the pool’s “front door” and thinks it’s connected and asking for work, but the pool doesn’t know that.   I’m guessing that a Subscription request is needed to convince the 2nd tier of the mining pool to send work to each already-connected client.  What I saw last night on the official pool is what I saw on Peak-pool when I filed the Issue above.  I believe the same thing happened on the official pool in July, too, when the deeper part of it was restarted and connected clients did not receive new work until the miners were restarted
AdiDev — Today at 10:57 AM
Thanks for the detailed response! 🙏🏽I’ll share this with the dev team.
ProductGuy — Today at 10:58 AM
Great, you’re welcome! Of course the desired user experience is that the miner “just starts getting work again” without the owner having to do anything, permitting high reliability of hands-off mining despite and after pool issues and restarts.
jason — Today at 7:34 PM
We have a project tracking these types of issues, they are high priority. Having to restart our AWS machines is really not ideal and must be fixed before main net launch.

-=-=-=--

Additional similar prior history on the Official Pool on 9july22:

https://discord.com/channels/771503434028941353/816795916627345450/995443199655022632

ProductGuy — 07/09/2022
Devs: official pool is having trouble for the last couple of hours. Disconnects, 0 hashrate, etc.  around 1-2:30 PM PDT Saturday 9july.   Mining is currently not working for me - 2 miners are trying but have 0 hashrate.  Been intermittent.
ProductGuy — 07/09/2022
@AdiDev @jason  I don't know if anyone would look at this over the weekend, but wanted someone on the team to see it.  Others have noticed it too and posted in miningpool-general.  My 2 miners are still in a state of "subscribing to the pool for work", then 0 MH/s.
AdiDev — 07/09/2022
Hi! I have shared this with the team. Please allow us to get back to you guys ASAP

jason — 07/10/2022
We're working on it now. Thanks for bringing this up.

**Comment by hughy** [comment] 2022-09-12 19:22
I tried to reproduce this problem when the pool went down last week (9/8).

After restarting, the pool node was behind the main chain by about 700 blocks. While the pool node was syncing the pool did not send out any new work, and my miner's hashrate was 0. Once the pool node was synced (after an hour or so), new work went out and my miner had non-zero hashrate.

I'll try again to reproduce this by running a pool locally, but I think that the issue may be that the pool falls out of sync when it goes down.

**Comment by holahula** [comment] 2023-04-20 22:28
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue

**Closed by holahula** 2023-04-20 22:28 UTC
Labels: bug, verified
