### ISSUE TITLE
lost account

### ISSUE THREAD

**Issue by msa6867** [iron-fish/ironfish#1406] opened 2022-05-15 08:02 UTC
### What happened?

After computer shut off unexpectedly (killing both the node and mining processes), the default account under which I had been mining and accumulating $IRON was lost from my account list and unusable.  I had originally created the account name "msa6867" as my default account and had been assigned  public key: 0d87e848ff1bb16e7dc10e4aeca517b3e906cef570b3af9a065ab061b63dee19b15c8f5964170be049b889

I restarted  IRONFISH node and miner, but all attempts to locate my account were fruitless.  accounts:use resulted in error stating account did not exist and accounts:list returned a null set.  In order to continue participating in mining I created a new account with the same name and was assigned public key: fcf77bf384221f25ae90583dc62ade76f43b5c5bfb8403b0a636c7f2d663eecab45a3ff2272a1b7c8da665
which I have been using since

### Version

v0.1.32

### Debug output

```shell
Iron Fish version       0.1.32 @ 1abccc9
Iron Fish library       0.0.10 @ 1abccc9
Operating system        Windows_NT x64
CPU model(s)            AMD Ryzen 3 4300G with Radeon Graphics
CPU threads             8
RAM total               7.37 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
```

### Graffiti

msa6867

**Comment by adi7dev** [comment] 2022-06-10 18:00
You created another account with an identical username i.e. even case sensitive?

**Comment by msa6867** [comment] 2022-06-10 18:13
unfortunately I did... I was not considering at the time that this may
create a problem.   Seeing that the first account seemed completely lost, I
was not sure it mattered.

On separate note... I exported the new account msa6867 in order to switch
computers; when I imported the account on the new computer after getting
ironfish up and running, the account balance showed zero.  I know this is a
separate issue and should probably open a new ticket for that.

**Comment by lwisne** [comment] 2022-08-03 23:07
As far as I know we have never seen this behavior with an account just disappearing. There likely isn't anything we can do to recover. Are you sure you weren't running with a datadir flag or some other option that may have cause this behavior?

**Comment by msa6867** [comment] 2022-08-04 00:41
Yes I am sure.  And it was my fault to name a new account by the same name after the first disappeared, as I am sure that destroyed whatever paper trail there might have been.

**Comment by danield9tqh** [comment] 2022-11-02 00:29
Going to close this since we don't have any viable leads on a root cause

**Closed by danield9tqh** 2022-11-02 00:29 UTC
Labels: bug, needs verification
