### ISSUE TITLE
Reduced hashrate after update to 0.15

### ISSUE THREAD

**Issue by alar0n** [iron-fish/ironfish#828] opened 2021-12-23 12:14 UTC
VM with 48 vCPU and 128GB mem on Server with 2 CPU 6248R Xeon gold. In top hashrate before update to 0,15, in bottom- after update. Ubuntu 20.10.
![image](https://user-images.githubusercontent.com/31000576/147238084-0a56a147-c6c8-45e9-a07f-7fb18576080b.png).

If increase on this VM vCPU to 96 and start with 96 threads result will be more worse:
![image](https://user-images.githubusercontent.com/31000576/147238395-b346de7f-918b-454b-b7c3-59deab9f85b9.png)

And next some experimentals on this VM. decrease and increase of threads:
![image](https://user-images.githubusercontent.com/31000576/147238985-46de910b-5ad0-49bc-bf42-f428f705b790.png)

It seems to me that only one processor is used on multiprocessor servers.

**Comment by Vovans** [comment] 2021-12-23 14:03
Can be confirmed by other community members. A column "1 or 2 CPU" with the value 2 provides the information of performance for two CPUs servers

https://docs.google.com/spreadsheets/d/11jBSRHlNVL8MhC3BaNtPx2lK5KlNhomw1nYazoT8xI4/edit?usp=sharing

**Comment by jTiKey** [comment] 2022-01-11 20:16
Same here on 2nd Gen AMD EPYC

**Comment by alar0n** [comment] 2022-01-21 03:15
On a 4-processor system, after updating to 0.1.20, using the -t -1 option loads only one processor.
on a 2-processor system, both are loaded by 90%

**Comment by NullSoldier** [comment] 2022-01-21 06:01
> On a 4-processor system, after updating to 0.1.20, using the -t -1 option loads only one processor. on a 2-processor system, both are loaded by 90%

What is the issue here? You're talking about CPU utilization? Are you saying it's not spawning the correct number of workers, or that you expect your CPU load to be higher?

If the issue is you just expect CPU load to be higher than you'll have to write your own miner to get that higher.

I'm closing this ticket as users are getting much higher hash rate, and it's no longer related because as the maintainers of the coin it's not our job to implement an efficient miner. Consider the included miner a demo miner, and we expect you the community to build a more efficient one.

**Closed by NullSoldier** 2022-01-21 06:01 UTC

**Comment by NullSoldier** [comment] 2022-01-21 06:02
Closed because 0.1.20 has solved this issue which was a slight reduction in hash power for some users because of the `blake3-native` library. If there are any further issues and complaints about you wanting higher CPU utilization from our built in miner, or higher hash rate then we welcome and encourage you to write your own miner.
