### ISSUE TITLE
broken links in README

### ISSUE THREAD

**Issue by wd021** [iron-fish/ironfish#986] opened 2022-02-10 22:30 UTC
### What happened?

Reading through the docs and the links to 'Captain' are broken.

![Screenshot 2022-02-10 at 22 29 33](https://user-images.githubusercontent.com/2752586/153507530-c6684462-f602-481a-9d8f-cf1927b369f0.png)
!

**Comment by deekerno** [comment] 2022-02-11 01:31
Duplicate of #965.

**Closed by deekerno** 2022-02-11 01:31 UTC
Labels: bug
