### ISSUE TITLE
after update why so many fork?

### ISSUE THREAD

**Issue by shandongdacongge** [iron-fish/ironfish#741] opened 2021-12-14 07:01 UTC
after update to the new version 0.1.10,
the node has lots of forl seq, and  lots of recorganizing chain ,and  lots of   Transaction expired  and so on

I think it is unnormal?
how to resolve it ?
anyone knows?
![image](https://user-images.githubusercontent.com/64308935/145948549-5fc71ba6-c3af-495c-b174-113900ff8416.png)

**Comment by gjfrn** [comment] 2021-12-20 00:38
Duplicate of #731

**Closed** 2022-07-23 02:00 UTC
