### ISSUE TITLE
Transaction failed but increased wallet balance

### ISSUE THREAD

**Issue by justmml** [iron-fish/ironfish#1629] opened 2022-06-15 13:53 UTC
### What happened?

Making `ironfish deposit` increased my balance by 0.1 $IRON + 0.00000001 $IRON transaction fee.
Balance before transaction: $IRON 0.51072778 ($ORE 51,072,778)
Balance after transaction: $IRON 0.61072779 ($ORE 61,072,779)

Transaction link: https://explorer.ironfish.network/transaction/ecf3abdc0cee6cdd2497d9c855b675ad97485b7f68dde39f7e96983605646889
![изображение](https://user-images.githubusercontent.com/8207807/173844389-d00fcb14-69ba-4c45-823b-caa265e94c3b.png)

### Version

v0.1.36

### Debug output

```shell
Iron Fish version       0.1.36 @ src
Iron Fish library       0.0.14 @ src
Operating system        Linux x64
CPU model(s)            AMD EPYC 7282 16-Core Processor
CPU threads             4
RAM total               7.77 GiB
Node version            v16.15.1
ironfish in PATH        true
Telemetry enabled       true
```

### Relevant log output

```shell
root@vmi881185:~# ironfish deposit
yarn run v1.22.18
$ yarn build && yarn start:js deposit
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run deposit

You are about to send $IRON 0.10000000 ($ORE 10,000,000) plus a transaction fee of $IRON 0.00000001 ($ORE 1) to the Iron Fish deposit account.
Your remaining balance after this transaction will be $IRON 0.51072778 ($ORE 51,072,778).
The memo will contain the graffiti "mml_node".

* This action is NOT reversible *

Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s

Depositing $IRON 0.10000000 ($ORE 10,000,000) from mml_wallet
Transaction Hash: ecf3abdc0cee6cdd2497d9c855b675ad97485b7f68dde39f7e96983605646889
Transaction fee: $IRON 0.00000001 ($ORE 1)

Find the transaction on https://explorer.ironfish.network/transaction/ecf3abdc0cee6cdd2497d9c855b675ad97485b7f68dde39f7e96983605646889 (it can take a few minutes before the transaction appears in the Explorer)
Done in 1917.91s.
root@vmi881185:~# ironfish accounts:balance
yarn run v1.22.18
$ yarn build && yarn start:js accounts:balance
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run accounts:balance
Account - mml_wallet (cdca06c)

The balance is: $IRON 0.61072779 ($ORE 61,072,779)
Amount available to spend: $IRON 0.61072779 ($ORE 61,072,779)
Done in 563.66s.
```

### Graffiti

mml_node

**Comment by mat-if** [comment] 2022-06-15 22:05
Hi @justmml, thanks for reporting this.

If I'm understanding correctly, this is expected behavior.

The deposit command is telling you what your balance will be _after_ the transaction is made. Here, it's saying your balance will be 0.51072778 (which if we add 0.1 deposit amount + 0.00000001 tx fee shows what your balance would be prior to the deposit: 0.61072779)

But since the transaction doesn't get put into a block, it expires, which would leave your balance where it was prior to the deposit, which would be 0.61072779 (which is 0.51072778 + 0.1 deposit amount + 0.00000001 transaction fee).

I'm going to go ahead and close this, but feel free to re-open or reply if I'm missing something

**Closed by mat-if** 2022-06-15 22:05 UTC
Labels: bug
