### ISSUE TITLE
Error. Code 'WS_ERR_UNEXPECTED_RSV_2_3',   [Symbol(status-code)]: 1002

### ISSUE THREAD

**Issue by msa6867** [iron-fish/ironfish#1786] opened 2022-07-14 06:09 UTC
### What happened?

started ironfish in one CLI, started mining (after syncing) in another CLI and  attempted three deposits (after syncing) in third CLI.  Two depoists showed as completed but never appeared in block explorer.  The third deposit froze. Meanwhile the log output on the running node turned to gibberish followed by a legible error sequence as shown below.

### Version

v0.1.37

### Debug output

```shell
Iron Fish version            0.1.37 @ 44a7990
Iron Fish library            0.0.15 @ 44a7990
Operating system             Windows_NT x64
CPU model(s)                 AMD Ryzen 9 5950X 16-Core Processor
CPU threads                  32
RAM total                    31.92 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           000000000008db24a795b4c8aa80596ce2eb4a1fd9ad7709103a8e776f77e02a
Accounts head in chain       true
Accounts head sequence       92703
```

### Relevant log output

```shell
�↔i۲▼�U�����=��i���ڌd3�☻�→�1�x�q��n�������@oD6♥!�♣�
áڗ8<�}�`�→�nY>VMFՋGԤ_�.�D�¶��2ؿ.C��_�0↔�u�(L��¶ VB���|�O�
�~♣�a
��→�)▼H2�,�����♣☺☻(9j☺��‼�|��;
��↕��0r敘��)�kp♦�~x☻DZY�&����H�!�d����$�v�
Tb�R�I§�1�
�S��a�;�[       �J�y�N�6Gee�ZȪ�1�
���f̊���^�♦��¶!檙�3������2(�_�g↓���.������<K�ʠ�I���]魭}�∟�↑��.g��(z4���↑o�ŃvS_Ú�►�ʿ↨E�∟p_���↕��h��?ͬ�����]��r�◄��i�♣[↕ѥ/K�˷�, LǞ��▬♣�R+�B[+�+z��an�WL!聥 ▼Х���◄��p��x��<�[☺j9G�-K�q�%2�1@��.~k���◄���X§� �[��fXG��↨�
/����♣,♠ފ�~�?��o→y�"��)��{�ͱ}♣���Jq�§���GֻA
�����gwJۙ�G�Y��♦7∟�h
��.�P↑"�EZ0>‼T;�
@L♦�♥UP2�♣��☺�Q�
#�x��▲‼��8iB�Q♠�▬�A♦P�mɸ�7%�7�Z6E�♣‼↓�g�!�o^E_G�Bb�R§�+�>1�յ�d��E�♦Q��→�6fW�♣�[ǃM��
{���uBZ��bd�5�☻�;‼"�0↔����۪☺�1�`�q¥�p)�§���d
�↓u↑�}j�v‼
ݓ�o��↔����V▲◄��^$�5�b�▬5�9b��↕�m4<�b� ♥h($�@w(E9C�      ����*NcX�+J↓�bJ�►☺�'J����^���#�+�(�AyZ�►��U��Ǉ��-%O���~'V<�H|▬~p�$S↕�o��$^P↔�2�L�-�>��@�@8�U��-P→�      i���.�L3�dN�sn�X7hW�諮&'ݾw�b��n"H��ЬH?♣9��s=�:{6◄��B¶����
J�☺�mq↑�Q]�>��EB�Q `j2Ґ'�A↓�c���9ȁ��{♣i§m��§
h�¶�0��
�a�5|�wg�o���!▬U[P�P�NP�Ʃϼ�[����W|4gp�8��nKÙ�D:►z�      Ҙ�Y�7*�WРe��3�!�♦O�'|♣8��m�"_������ޯ1<♣Ɍ☺u
27��B�,X3x�ӾI7����E�U��i�M3�){��{/�m��∟♦Ė�x��.�ň
�r��+ŀ3R��Fϲ�#;→��B��z�↓�{cu�A$f↔�♦흜i��+�ކ→�'�☻�↑=�♠$�UB�‼▼��#jd�k     ��      B�tM�
�M���↔^�-�T♦wpI&�(X��B۬�T�F�����▬�-^↕8�Ml�;<��U��)��f����4�f��IwL�f�#��{�ϓ{}J4�{(G}$4_1V��F|�6�ƈݐW[�Z�A �J����z�:�
�[��o�►�qd��v
vx§)��B�� _�y☺,(�?6�S���☻�i�d>
�♦�K8g�Ĉ��@z^�0�>��
۪��^Orе��x���"�3♦�j>�\�▼☺�≹��C►k��y-�l`I�o<��☺)&�
↨{PH�&��ER*k��5♦5�vz�↑���‼��ǩ
����Ov4�Vz�M$4�]�♥��k�g02.p�o`.ۜ�D���R�mHjo♣��0��a�K�P�;�u%     $�C�O.�\�5��1� p�☺�]Q��^�����-Cj7F�}��X�!~1��Z��/|�-ߟ!�
伐qAEL�;W�WǶ�����↑��@�3�+z��an�WL!聥 ▼Х���◄��p��x��<�[☺��T0ҽ�t☺�G+�0�$�"T�Y�P��!�b���↓p�↓�H¶K�w�\c���   �����↑V�>→I�H�x]s%∟vE\�
��31M�N↑��י�$y�‼��
�`E%�>5�ݾ�^mCպ�����+��9�t�Uݏ8�◄�dv��U�D{rՓ�→'�ٸ�s���ۏS^X�~↕�
�"�☺�↓3*�§^��↨����է�♦!6♣�[��W����ݴ��C�4F���▲�S��ԬR��p���u����!RYs�鼭h�����5,3∟�/
8�.�]�s�E�^�#ŗ�♣�=�}�c�#[�u�
��n�↑V=Za\��4X�►9q��M�[ݬ.f��kU�]►C�u�#��→¶&�§�(↕$e�,�@�Ց�1�N��T�l�P�☺����Xg����*���¶��X,����►чm♠↓��ދ�U_��↑Cva��V>�}�B☺���m�&G↨
N�▲��ۈd�(�E��9�3j�����Cɠ�(�MS↓��W�
q�5���y�)∟�hXS,��\��K♠��� X�∟�k-?���@↕�G�9�釡)�☺��eb\��󏨾�� ♥�.�B�?↑�uk�˒v-���z�}��m�
y�RK@�∟�-)�?F���u��ؔms�{u-↕O
>-§��z�d�↕��:d��Zw]s��Ȼ↕�.��[���,'m��*T%��k�♠c��E���7�0Z9��kr☺%<���?V�▬▲�x�[$�I�
�^S���VАcK����▼�:◄�9���Lk�U��poP�� *D�}V��5dlK�☻♦▼�����D��|�k♥‼�Y�VmC�xԬ֣F*䝶G♦�B�S∟$7�8iyF�
�$2ȸ�0����v��
�א`��
(eZ�∟8!t1��mru�S��k#��w▼{~'"2�∟♥↑6? �§�~|\J��e�7��s/��/�♣
node:events:505
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
    at Receiver.getInfo (C:\Users\Mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:171:14)
    at Receiver.startLoop (C:\Users\Mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:131:22)
    at Receiver._write (C:\Users\Mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Receiver.Writable.write (node:internal/streams/writable:334:10)
    at Socket.socketOnData (C:\Users\Mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\websocket.js:920:35)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (C:\Users\Mark\AppData\Roaming\npm\node_modules\ironfish\node_modules\ws\lib\websocket.js:826:13)
    at Receiver.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'WS_ERR_UNEXPECTED_RSV_2_3',
  [Symbol(status-code)]: 1002
}
```

### Graffiti

msa6867

**Comment by wd021** [comment] 2022-08-02 07:58
are you able to reproduce this error?

**Comment by holahula** [comment] 2023-04-20 22:22
Closing due to staleness. If the issue persists - please file a new issue

**Closed by holahula** 2023-04-20 22:22 UTC
Labels: bug, needs verification
