### ISSUE TITLE
memory leaks increased after upgrade to 0.1.41

### ISSUE THREAD

**Issue by gzivdo** [iron-fish/ironfish#1933] opened 2022-08-04 20:22 UTC
### What happened?

This nodes do not send transactions after restart, but memory usage grow very fast
![изображение](https://user-images.githubusercontent.com/13568002/182945064-68e86ebe-bdb9-4ab1-92cf-284b95eaff3a.png)
![изображение](https://user-images.githubusercontent.com/13568002/182945203-c1bff953-4abf-472e-8b6c-5810905c6950.png)
![изображение](https://user-images.githubusercontent.com/13568002/182945331-c8edaf9f-eb6c-4107-8792-58d722899216.png)
fallback is node restart

### Version

0.1.41

### Graffiti

ar2Obyahain

**Comment by lwisne** [comment] 2022-08-05 15:35
Thank you for the feedback. Going to add to the larger memory leak thread - this is very high priority and we have people looking at it right now.

**Comment by lwisne** [comment] 2022-08-05 15:35
Duplicate of https://github.com/iron-fish/ironfish/issues/1925

**Closed by lwisne** 2022-08-05 15:35 UTC
Labels: bug
