### ISSUE TITLE
After upgrade to 0.1.24, node stopped unexpectedly.

### ISSUE THREAD

**Issue by onecooler** [iron-fish/ironfish#1049] opened 2022-02-19 16:04 UTC
### What happened?

After upgrade to 0.1.24 node has started, but stopped after a while with the following trace in journal:

> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]: /root/ironfish/ironfish/build/src/primitives/noteEncrypted.js:40
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:         const note = this.takeReference().decryptNoteForSpender(spenderHexKey);
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:                                           ^
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]: Error: Failed to unwrap shared reference of `NativeNoteEncrypted` type from napi value
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at NoteEncrypted.decryptNoteForSpender (/root/ironfish/ironfish/build/src/primitives/noteEncrypted.js:40:43)
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at Accounts.decryptNotes (/root/ironfish/ironfish/build/src/account/accounts.js:243:40)
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at /root/ironfish/ironfish/build/src/account/accounts.js:272:32
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at Transaction.withReference (/root/ironfish/ironfish/build/src/primitives/transaction.js:45:24)
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at Accounts.syncTransaction (/root/ironfish/ironfish/build/src/account/accounts.js:271:27)
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at /root/ironfish/ironfish/build/src/account/accounts.js:45:28
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at async Promise.all (index 0)
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at async Event.emitAsync (/root/ironfish/ironfish/build/src/event.js:64:9)
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at async ChainProcessor.add (/root/ironfish/ironfish/build/src/chainProcessor.js:37:9)
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at async ChainProcessor.update (/root/ironfish/ironfish/build/src/chainProcessor.js:80:13) {
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:   code: 'InvalidArg'
> Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]: }
> Feb 19 16:41:41 vmi789940.contaboserver.net yarn[271166]: error Command failed with exit code 1.
> Feb 19 16:41:41 vmi789940.contaboserver.net yarn[271166]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> Feb 19 16:46:01 vmi789940.contaboserver.net systemd[1]: Stopping IronFish Node...
> Feb 19 16:46:01 vmi789940.contaboserver.net systemd[1]: ironfishd.service: Main process exited, code=exited, status=1/FAILURE
> Feb 19 16:46:01 vmi789940.contaboserver.net systemd[1]: ironfishd.service: Failed with result 'exit-code'.
> Feb 19 16:46:01 vmi789940.contaboserver.net systemd[1]: Stopped IronFish Node.
This issue has appeared once after upgrade. I am monitoring the server and if I face this again, I will update this one.

### Version

0.1.24

### Relevant log output

```shell
Feb 19 13:38:57 vmi789940.contaboserver.net yarn[271204]: Connected to the Iron Fish network
Feb 19 13:39:07 vmi789940.contaboserver.net yarn[271204]: Starting sync from aY8aFZ4 (richard). work: +85684446990868, ours: 120424, theirs: 120427
Feb 19 13:39:07 vmi789940.contaboserver.net yarn[271204]: Finding ancestor using linear search on last 3 blocks starting at 00000...dce6e (120424) from peer aY8aFZ4 (richard) at 120427
Feb 19 13:39:07 vmi789940.contaboserver.net yarn[271204]: Found peer aY8aFZ4 (richard) ancestor 00000...dce6e, syncing from 120424 -> 120427 (3) after 1 requests
Feb 19 13:39:07 vmi789940.contaboserver.net yarn[271204]: Requesting 20 blocks starting at 00000...dce6e (120424) from aY8aFZ4 (richard)
Feb 19 13:39:08 vmi789940.contaboserver.net yarn[271204]: Finished syncing 3 blocks from aY8aFZ4 (richard)
Feb 19 13:49:40 vmi789940.contaboserver.net yarn[271204]: Added block seq: 120440, hash: 00000...6d9e3, txs: 1, progress: 100.00%, time: 54.1ms
Feb 19 14:12:50 vmi789940.contaboserver.net yarn[271204]: Added block seq: 120460, hash: 00000...2604b, txs: 1, progress: 100.00%, time: 51.0ms
Feb 19 14:26:21 vmi789940.contaboserver.net yarn[271204]: Added block seq: 120480, hash: 00000...0ba82, txs: 1, progress: 100.00%, time: 56.3ms
Feb 19 14:48:44 vmi789940.contaboserver.net yarn[271204]: Added block seq: 120500, hash: 00000...3f2fc, txs: 1, progress: 100.00%, time: 59.5ms
Feb 19 15:04:03 vmi789940.contaboserver.net yarn[271204]: Added block seq: 120520, hash: 00000...fb55a, txs: 1, progress: 100.00%, time: 58.6ms
Feb 19 15:12:46 vmi789940.contaboserver.net yarn[271204]: Reorganizing chain from 00000...5b730 (120534) for 00000...daab2 (120534) on prev 00000...9f9c4 (120533)
Feb 19 15:12:46 vmi789940.contaboserver.net yarn[271204]: Reorganized chain. blocks: 1, old: 00000...5b730 (120534), new: 00000...9f9c4 (120533), fork: 00000...9f9c4 (120533)
Feb 19 15:22:18 vmi789940.contaboserver.net yarn[271204]: Added block seq: 120540, hash: 00000...a7b3f, txs: 2, progress: 100.00%, time: 202.6ms
Feb 19 15:41:01 vmi789940.contaboserver.net yarn[271204]: Added block seq: 120560, hash: 00000...5628a, txs: 1, progress: 100.00%, time: 60.0ms
Feb 19 16:04:28 vmi789940.contaboserver.net yarn[271204]: Added block seq: 120580, hash: 00000...257ea, txs: 2, progress: 100.00%, time: 135.3ms
Feb 19 16:23:41 vmi789940.contaboserver.net yarn[271204]: Added block seq: 120600, hash: 00000...610b7, txs: 1, progress: 100.00%, time: 76.0ms
Feb 19 16:34:40 vmi789940.contaboserver.net yarn[271204]: Reorganizing chain from 00000...79977 (120615) for 00000...feeb6 (120615) on prev 00000...96887 (120614)
Feb 19 16:34:40 vmi789940.contaboserver.net yarn[271204]: Reorganized chain. blocks: 1, old: 00000...79977 (120615), new: 00000...96887 (120614), fork: 00000...96887 (120614)
Feb 19 16:36:45 vmi789940.contaboserver.net yarn[271204]: Added block to fork seq: 120423, head-seq: 120615, hash: 00000...448ce, head-hash: 00000...feeb6, work: 807142450538533320, head-work: 812686228132>
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]: Added block seq: 120620, hash: 00000...c7544, txs: 1, progress: 100.00%, time: 42.5ms
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]: /root/ironfish/ironfish/build/src/primitives/noteEncrypted.js:40
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:         const note = this.takeReference().decryptNoteForSpender(spenderHexKey);
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:                                           ^
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]: Error: Failed to unwrap shared reference of `NativeNoteEncrypted` type from napi value
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at NoteEncrypted.decryptNoteForSpender (/root/ironfish/ironfish/build/src/primitives/noteEncrypted.js:40:43)
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at Accounts.decryptNotes (/root/ironfish/ironfish/build/src/account/accounts.js:243:40)
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at /root/ironfish/ironfish/build/src/account/accounts.js:272:32
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at Transaction.withReference (/root/ironfish/ironfish/build/src/primitives/transaction.js:45:24)
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at Accounts.syncTransaction (/root/ironfish/ironfish/build/src/account/accounts.js:271:27)
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at /root/ironfish/ironfish/build/src/account/accounts.js:45:28
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at async Promise.all (index 0)
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at async Event.emitAsync (/root/ironfish/ironfish/build/src/event.js:64:9)
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at async ChainProcessor.add (/root/ironfish/ironfish/build/src/chainProcessor.js:37:9)
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:     at async ChainProcessor.update (/root/ironfish/ironfish/build/src/chainProcessor.js:80:13) {
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]:   code: 'InvalidArg'
Feb 19 16:41:40 vmi789940.contaboserver.net yarn[271204]: }
Feb 19 16:41:41 vmi789940.contaboserver.net yarn[271166]: error Command failed with exit code 1.
Feb 19 16:41:41 vmi789940.contaboserver.net yarn[271166]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Feb 19 16:46:01 vmi789940.contaboserver.net systemd[1]: Stopping IronFish Node...
Feb 19 16:46:01 vmi789940.contaboserver.net systemd[1]: ironfishd.service: Main process exited, code=exited, status=1/FAILURE
Feb 19 16:46:01 vmi789940.contaboserver.net systemd[1]: ironfishd.service: Failed with result 'exit-code'.
Feb 19 16:46:01 vmi789940.contaboserver.net systemd[1]: Stopped IronFish Node.
```

**Comment by mat-if** [comment] 2022-02-22 16:12
Going to close this as it is a duplicate of https://github.com/iron-fish/ironfish/issues/1022. Thanks for submitting this, the more data we have, the better. It's just easier for us to track it in one issue

**Closed by mat-if** 2022-02-22 16:12 UTC
Labels: bug
