### ISSUE TITLE
Memory Leak[issue name]

### ISSUE THREAD

**Issue by bashkirov1960** [iron-fish/ironfish#1367] opened 2022-05-13 09:58 UTC
### What happened?

A bug happened!
Expected: 8 GB of RAM is enough to run a node.
Actual: after starting a node with "ironfish start" command memory leak occurs. Screenshot before typing "ironfish start" command, please look at RAM at the bottom of screenshot. It is 1,30 GB.
![2022-05-13](https://user-images.githubusercontent.com/79743419/168253597-5a989523-0991-4e8a-a587-280e7bd6d582.png)
In an hour we have 9.56 GB used.
![Sample4](https://user-images.githubusercontent.com/79743419/168254827-f6ce6682-8446-4b22-9daf-7c6cbb067114.png)
Soon RAM used will gradually go to a little bit more than 15 GB and stops working.
![2022-05-13 (2)](https://user-images.githubusercontent.com/79743419/168255672-746d95f5-98f6-4a81-8d02-1fa52504870e.png)
Checked several times. Installed with ngm. Ubuntu 20.04. 2 other nodes on other ubuntu 20.04 servers installed in the same way run smoothly - no memory leaks.

### Version

v0.1.32

### Debug output

```shell
Iron Fish version            0.1.32 @ 1abccc9
Iron Fish library            0.0.10 @ 1abccc9
Operating system             Linux x64
CPU model(s)                 Intel Xeon Processor (Cascadelake)
CPU threads                  6
RAM total                    15.63 GiB
Node version                 v16.15.0
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           000000000021f6bd0fe81819295a4461f010253693362fd3dac9d9f26c997a9f
Accounts head in chain       true
Accounts head sequence       3571
```

### Graffiti

veidsvi

**Comment by bashkirov1960** [comment] 2022-05-13 12:19
Sorry, the second screenshot was wrong. The right is here:
![2022-05-13 (1)](https://user-images.githubusercontent.com/79743419/168281525-7ef7b707-7139-4faa-a8c7-bf4855155220.png)

**Comment by lwisne** [comment] 2022-08-03 23:46
Duplicate of https://github.com/iron-fish/ironfish/issues/1925

**Closed by lwisne** 2022-08-03 23:46 UTC
Labels: bug, verified
