### ISSUE TITLE
Node randomly crashes with "error Command failed with exit code 1."

### ISSUE THREAD

**Issue by gjfrn** [iron-fish/ironfish#1794] opened 2022-07-15 22:18 UTC
### What happened?

The ironfish node randomly crashes ~ once a day. This behaviour started occurring since 0.1.38 and possibly 0.1.37.

### Version

0.1.38

### Relevant log output

```shell
Finished syncing 10 blocks from B5uAUqk (tetsugyo), skipped 10
Reorganizing chain from 00000...6757a (95224) for 00000...9fc48 (95224) on prev 00000...c688d (95223)
Reorganized chain. blocks: 1, old: 00000...6757a (95224), new: 00000...c688d (95223), fork: 00000...c688d (95223)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Graffiti

GFIRONFISH

**Comment by NullSoldier** [comment] 2022-07-18 01:12
We haven't seen this bug before. Does running the node with verbose logging reveal anything?

On a side note, it looks like you are using yarn. We strongly recommend not running from source, and using our NPM builds. There are steps to doing that here, https://ironfish.network/docs/onboarding/installation-iron-fish

**Comment by lwisne** [comment] 2022-08-03 16:25
We'll have to close this one without more verbose logging. Otherwise, we can't reproduce.

**Closed** 2023-02-27 22:26 UTC
Labels: bug, needs verification
