### ISSUE TITLE
ironfish config:edit doesnt work

### ISSUE THREAD

**Issue by aditya-manit** [iron-fish/ironfish#1002] opened 2022-02-13 16:55 UTC
### What happened?

I ran
```
ironfish config:edit
```
It throws the error
```
Editing /root/.ironfish/config.json
    Error: you must set the EDITOR environment variable or 'editor' in the ironfish config
```
I have set the editor to vim already and my env variable is also set
<img width="426" alt="Screenshot 2022-02-13 at 10 24 20 PM" src="https://user-images.githubusercontent.com/40714633/153765706-26e82484-494a-4cce-b142-d803e01d19fe.png">
<img width="260" alt="Screenshot 2022-02-13 at 10 25 01 PM" src="https://user-images.githubusercontent.com/40714633/153765729-7cd923ad-3ad5-4c86-b974-8cd77115ec6b.png">

### Version

ironfish-cli/0.1.21 linux-x64 node-v16.13.0

**Comment by Kupuyc** [comment] 2022-02-14 04:24
Duplicate of #964

**Comment by deekerno** [comment] 2022-04-18 19:36
Does this issue still persist after the latest update?

**Comment by lwisne** [comment] 2022-07-26 21:14
We believe this is now fixed. Let us know if you don't agree!

**Closed by lwisne** 2022-07-26 21:14 UTC
Labels: bug

**Comment by aditya-manit** [comment] 2022-10-22 07:34
Hey @lwisne I never received any testnet credits for this issue

**Comment by aditya-manit** [comment] 2022-10-30 07:58
Hey @lwisne just bumping this up
