### ISSUE TITLE
versions 37 & 36 incompatibility

### ISSUE THREAD

**Issue by rusyaboltaev** [iron-fish/ironfish#1714] opened 2022-06-30 14:31 UTC
### Description

If pool on version 0.1.37 ironfish-miner 0.1.36 cant get work before restart:

jun 30 06:27:30 vm-ironfish yarn[1318434]: Successfully connected to pool
jun 30 06:27:30 vm-ironfish yarn[1318434]: Listening to pool for new work

 and cant get graffiti after miner restart:
jun 30 14:20:48 vm-ironfish yarn[244718]: Waiting for graffiti from pool...

![image](https://user-images.githubusercontent.com/70545805/176703489-68e2997b-8629-4fd7-946e-442edbbf93ca.png)

**Comment by QustomQure** [comment] 2022-06-30 17:51
Working as intended. Please close this issue.

**Comment by rusyaboltaev** [comment] 2022-06-30 18:08
> Next time you should read announcements on discord first
> 
> https://discord.com/channels/771503434028941353/816795744680935445/991468505910218852

What should i read here? 
If are yout talking about "This will require you to upgrade your miner by the next major release or you will no longer be able to connect to the official Iron Fish pool", then it follows that backwards-compatibility will be broken with a version of X.Y.Z where X is greater than 0 (0.1.37 - MAJOR.MINOR.PATCH). In this case, a PATCH version was released. According to generally accepted specifications, a PATCH version should not break the backward-compatibility of subsequent releases.

**Comment by NullSoldier** [comment] 2022-07-01 19:07
There shouldn't be any breaking changes with this release. If there is a breaking change, that's unintended. I'll test this an get back to you.

**Comment by rusyaboltaev** [comment] 2022-07-07 21:13
> There shouldn't be any breaking changes with this release. If there is a breaking change, that's unintended. I'll test this an get back to you.
> 
> We don't use semantic versioning, we only ever increase the patch version, but attempt to maintain backwards compatibility. We're not focused on backwards compatibility as much during the test net as were optimizing for velocity of development for now.

It's not clear why you use semantic versioning terminology if you don't use it. 
So ok, waiting for answer and my points.

**Comment by lwisne** [comment] 2022-08-03 17:36
This was unintended, appreciate the report. Our versioning doesn't follow semantic versioning, apologies if there was any sign that this is the case.

Will give points here - thanks for the feedback!

**Closed by lwisne** 2022-08-03 17:36 UTC
Labels: bug, verified
