### ISSUE TITLE
[chain:repair -- force: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory]

### ISSUE THREAD

**Issue by JuManjey** [iron-fish/ironfish#1503] opened 2022-05-25 12:29 UTC
### What happened?

I trying to execute command:
`yarn --cwd ~/ironfish/ironfish-cli/ start chain:repair --force`
OR
`ironfish chain:repair --force`

Process going about 2 minutes and then crash.
Duplicate of  #
The same thing on my second server: AMD EPYC-32-Core/128 RAM 

Without of `--force`:
```
Repairing head chain tables: 
[========================================] 21231/21231 100% 0/sec | N/A
Skipping repair of merkle trees because it looks like they are valid.
If you want to force them to be repaired, use --force.
Repair complete.
Done in 9.02s.

```

### Version

0.1.35

### Debug output

```shell
yarn run v1.22.19
$ yarn build && yarn start:js debug
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run debug
Database in use, skipping output that requires database.
Stop the node and run the debug command again to show full output.

Iron Fish version       0.1.35 @ src
Iron Fish library       0.0.13 @ src
Operating system        Linux x64
CPU model(s)            Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
CPU threads             16
RAM total               125.71 GiB
Node version            v16.15.0
ironfish in PATH        true
Telemetry enabled       true
Done in 1.45s.
```

### Relevant log output

```shell
root@polygon ~ # yarn --cwd ~/ironfish/ironfish-cli/ start chain:repair --confirm --force
yarn run v1.22.19
$ yarn build && yarn start:js chain:repair --confirm --force
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node bin/run chain:repair --confirm --force
Opening node... done.
Clearing hash to next hash table... done
Clearing Sequence to hash table... done
Repairing head chain tables: [========================================] 21221/21221 100% 0/sec | N/A

Repairing MerkleTrees
Clearing notes MerkleTree... ⣾

<--- Last few GCs --->

[1952308:0x5ca36e0]   111482 ms: Scavenge 4048.3 (4125.6) -> 4044.6 (4127.1) MB, 15.0 / 0.0 ms  (average mu = 0.481, current mu = 0.440) task 
[1952308:0x5ca36e0]   111569 ms: Scavenge 4050.1 (4127.1) -> 4046.0 (4128.9) MB, 18.2 / 0.0 ms  (average mu = 0.481, current mu = 0.440) task 
[1952308:0x5ca36e0]   113270 ms: Scavenge 4051.7 (4128.9) -> 4047.4 (4145.9) MB, 1667.7 / 0.0 ms  (average mu = 0.481, current mu = 0.440) task 


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09c10 node::Abort() [/usr/bin/node]
 2: 0xa1c193 node::FatalError(char const*, char const*) [/usr/bin/node]
 3: 0xcf8dbe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0xcf9137 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0xeb09d5  [/usr/bin/node]
 6: 0xec069d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 7: 0xf23864 v8::internal::ScavengeJob::Task::RunInternal() [/usr/bin/node]
 8: 0xdb6f4b non-virtual thunk to v8::internal::CancelableTask::Run() [/usr/bin/node]
 9: 0xb77a54 node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) [/usr/bin/node]
10: 0xb798b9 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/usr/bin/node]
11: 0x1564936  [/usr/bin/node]
12: 0x1577064  [/usr/bin/node]
13: 0x1565288 uv_run [/usr/bin/node]
14: 0xa43dd5 node::SpinEventLoop(node::Environment*) [/usr/bin/node]
15: 0xb4bdb6 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/usr/bin/node]
16: 0xacd592 node::Start(int, char**) [/usr/bin/node]
17: 0x7f3b38f18083 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
18: 0xa4067c  [/usr/bin/node]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Graffiti

ironfishone1534

**Comment by Megavolv** [comment] 2022-06-20 16:05
The same error:
```
Repairing MerkleTrees
Clearing notes MerkleTree... ⣽

<--- Last few GCs --->

[303764:0x54f06a0]   116974 ms: Mark-sweep 4051.8 (4139.1) -> 4041.5 (4142.1) MB, 3838.3 / 0.0 ms  (average mu = 0.071, current mu = 0.022) task scavenge might not succeed
[303764:0x54f06a0]   120824 ms: Mark-sweep 4054.5 (4142.1) -> 4044.2 (4144.6) MB, 3791.0 / 0.0 ms  (average mu = 0.041, current mu = 0.015) task scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09c10 node::Abort() [/usr/bin/node]
 2: 0xa1c193 node::FatalError(char const*, char const*) [/usr/bin/node]
 3: 0xcf8dbe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0xcf9137 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0xeb09d5  [/usr/bin/node]
 6: 0xec069d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 7: 0xf23864 v8::internal::ScavengeJob::Task::RunInternal() [/usr/bin/node]
 8: 0xdb6f4b non-virtual thunk to v8::internal::CancelableTask::Run() [/usr/bin/node]
 9: 0xb77a54 node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) [/usr/bin/node]
10: 0xb798b9 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/usr/bin/node]
11: 0x1564936  [/usr/bin/node]
12: 0x1577064  [/usr/bin/node]
13: 0x1565288 uv_run [/usr/bin/node]
14: 0xa43dd5 node::SpinEventLoop(node::Environment*) [/usr/bin/node]
15: 0xb4bdb6 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/usr/bin/node]
16: 0xacd592 node::Start(int, char**) [/usr/bin/node]
17: 0x7f6c61d6d083 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
18: 0xa4067c  [/usr/bin/node]
```

**Comment by lwisne** [comment] 2022-08-03 23:38
Duplicate of https://github.com/iron-fish/ironfish/issues/1925

**Closed by lwisne** 2022-08-03 23:38 UTC
Labels: bug, verified
