### ISSUE TITLE
Balance mismatch in the blockchain

### ISSUE THREAD

**Issue by DrErfy** [iron-fish/ironfish#1797] opened 2022-07-16 13:11 UTC
### What happened?

![IronBug](https://user-images.githubusercontent.com/40718686/179356113-78d92dfc-7c87-4d56-92bc-1d556d11cc47.png)

When trying to execute "ironfish deposit", the error "unsufficient funds" is returned. However, 'if_node_info' shows that there are enough funds

### Version

0.1.35

### Debug output

```shell
Iron Fish version       0.1.35 @ 4bc3765
Iron Fish library       0.0.13 @ 4bc3765
Operating system        Linux x64
CPU model(s)            AMD Ryzen 9 5950X 16-Core Processor
CPU threads             32
RAM total               31.34 GiB
Node version            v16.13.0
ironfish in PATH        true
Telemetry enabled       true
```

### Graffiti

Erfish

**Comment by NullSoldier** [comment] 2022-07-18 01:27
Can you post what your balances are? I don't know what `if_node_info` is, because that's not ironfish command. What does `ironfish accounts:balance` show for both of your balances of confirmed and unconfirmed?

**Comment by lwisne** [comment] 2022-08-03 16:19
Going to close this if we don't get further info.

**Closed** 2022-12-08 23:33 UTC
Labels: bug, needs verification
