### ISSUE TITLE
node 0.1.41 cant start, ---- Error('nullifierToNote mappings must have a corresponding noteToNullifier map');

### ISSUE THREAD

**Issue by leoncryp** [iron-fish/ironfish#1928] opened 2022-08-04 16:04 UTC
### What happened?

i get the above title error when i run
`yarn ironfish start`
or 
`yarn ironfish start --upgrade`

previously on .40
```
git pull
yarn clean
yarn install
```
updated node to .41
also include the --upgrade
it said it changed something v6 to v10
Sorry, I lost the text coz i reset the pc, 
after i updated to .41 and run the normal 
`yarn ironfish start`
it said something about update from v6 to v10

yarn start status and cpu miner
works fine

for some reason 
`yarn ironfish depositAll`
seems to run, previous version require node to be up in order to deposit
it will start the node in the background, after I answer yes it will say
Fetching account balance...
60min later
error Command failed with exit code 2.

### Version

node 0.1.41
yarn v1.22.19

### Debug output

$ /home/t/ironfish/node_modules/.bin/ironfish start --upgrade
Version       0.1.41 @ src
Node Name     leoncryp
Graffiti      leoncryp
Peer Identity lJInNKVyml8PA1YzLzv6yrpV081aJCgkwne3L4R7wio=
Peer Agent    ironfish/0.1.41/src
Peer Port     9033
Bootstrap     test.bn1.ironfish.network
 
WebSocket server started at :::9033
/home/t/ironfish/ironfish/build/src/account/accounts.js:349
                        throw new Error('nullifierToNote mappings must have a corresponding noteToNullifier map');
                                       ^

Error: nullifierToNote mappings must have a corresponding noteToNullifier map
    at /home/t/ironfish/ironfish/build/src/account/accounts.js:349:31
    at async LevelupDatabase.withTransaction (/home/t/ironfish/ironfish/build/src/storage/database/database.js:39:28)
    at async Accounts.removeTransaction (/home/t/ironfish/ironfish/build/src/account/accounts.js:331:9)
    at async Accounts.expireTransactions (/home/t/ironfish/ironfish/build/src/account/accounts.js:672:17)
    at async Accounts.eventLoop (/home/t/ironfish/ironfish/build/src/account/accounts.js:156:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Relevant log output

[
![image](https://user-images.githubusercontent.com/40289699/182904407-b837fa8f-8f58-4aec-b644-453fbf979d89.png)
](url)
_No response_

### Graffiti

leoncryp

**Comment by leoncryp** [comment] 2022-08-04 16:37
[
![image](https://user-images.githubusercontent.com/40289699/182904181-d8c59e5b-3d9f-4f10-84f8-c73fdcdc22f9.png)
](url)

**Comment by leoncryp** [comment] 2022-08-04 17:38
t@t-B450NH:~/ironfish/ironfish-cli$ yarn ironfish migrations:start
yarn run v1.22.19
$ /home/t/ironfish/node_modules/.bin/ironfish migrations:start
All 3 migrations applied.
Done in 1.72s.
t@t-B450NH:~/ironfish/ironfish-cli$ yarn ironfish start --upgrade
yarn run v1.22.19
$ /home/t/ironfish/node_modules/.bin/ironfish start --upgrade

Version       0.1.41 @ src
Node Name     leoncryp
Graffiti      leoncryp
Peer Identity lJInNKVyml8PA1YzLzv6yrpV081aJCgkwne3L4R7wio=
Peer Agent    ironfish/0.1.41/src
Peer Port     9033
Bootstrap     test.bn1.ironfish.network
 
WebSocket server started at :::9033
/home/t/ironfish/ironfish/build/src/account/accounts.js:349
                        throw new Error('nullifierToNote mappings must have a corresponding noteToNullifier map');
                              ^

Error: nullifierToNote mappings must have a corresponding noteToNullifier map
    at /home/t/ironfish/ironfish/build/src/account/accounts.js:349:31
    at async LevelupDatabase.withTransaction (/home/t/ironfish/ironfish/build/src/storage/database/database.js:39:28)
    at async Accounts.removeTransaction (/home/t/ironfish/ironfish/build/src/account/accounts.js:331:9)
    at async Accounts.expireTransactions (/home/t/ironfish/ironfish/build/src/account/accounts.js:672:17)
    at async Accounts.eventLoop (/home/t/ironfish/ironfish/build/src/account/accounts.js:156:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
t@t-B450NH:~/ironfish/ironfish-cli$

**Comment by lwisne** [comment] 2022-08-04 18:53
Duplicate of https://github.com/iron-fish/ironfish/issues/1500

**Closed by lwisne** 2022-08-04 18:53 UTC
Labels: bug
