### ISSUE TITLE
Asset balance became 0 even the send command did not succeed.

### ISSUE THREAD

**Issue by cynic-1** [iron-fish/ironfish#3079] opened 2023-01-23 11:40 UTC
### What happened?

A bug happened!

I ran `ironfish wallet:send` with an amount slightly over my balance, the cli returned `Error: fractional component exceeds decimals`. 

I guess my input violated both `amount should <= balance` and `minimum precision` rule, so it should return an error. 

However, after the error, my asset balance became 0 while the command apparently did not succeed.

### Version

v0.1.62

### Debug output

```shell
C:\Users\song>ironfish wallet:balances
Account: default
 Asset Name Asset Id                                                         Confirmed Balance
 ────────── ──────────────────────────────────────────────────────────────── ─────────────────
 cynic      061b3f5d7f98d6108011d13b55bea09b45cd7a384a4fa6366019d139f240165f 1024.00000000
 $IRON      d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6 0.00000004

C:\Users\song>ironfish wallet:send
? Select the asset you wish to send 061b3f5d7f98d6108011d13b55bea09b45cd7a384a4fa6366019d139f240165f (cynic)
Enter the amount (balance: 1024.00000000): 1024.0000000000000000000000000001
Error: fractional component exceeds decimals [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT ] (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.7.0)
    at Logger.makeError (C:\Users\song\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ethersproject\logger\lib\index.js:238:21)
    at Logger.throwError (C:\Users\song\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ethersproject\logger\lib\index.js:247:20)
    at throwFault (C:\Users\song\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ethersproject\bignumber\lib\fixednumber.js:17:19)
    at Object.parseFixed (C:\Users\song\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ethersproject\bignumber\lib\fixednumber.js:101:9)
    at CurrencyUtils.decodeIron (C:\Users\song\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\utils\currency.js:21:28)
    at Send.start (C:\Users\song\AppData\Roaming\npm\node_modules\ironfish\build\src\commands\wallet\send.js:47:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Send.run (C:\Users\song\AppData\Roaming\npm\node_modules\ironfish\build\src\command.js:24:13)
    at async Send._run (C:\Users\song\AppData\Roaming\npm\node_modules\ironfish\node_modules\@oclif\core\lib\command.js:80:22)
    at async Config.runCommand (C:\Users\song\AppData\Roaming\npm\node_modules\ironfish\node_modules\@oclif\core\lib\config\config.js:272:25)

C:\Users\song>ironfish wallet:send
? Select the asset you wish to send 061b3f5d7f98d6108011d13b55bea09b45cd7a384a4fa6366019d139f240165f (cynic)
Enter the amount (balance: 0.00000000): 10
Enter the public address of the recipient: dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca
Enter the fee amount in $IRON (min: 0.00000001 recommended: 0.00000001) [0.00000001]:

You are about to send:
061b3f5d7f98d6108011d13b55bea09b45cd7a384a4fa6366019d139f240165f 10.00000000 plus a transaction fee of $IRON 0.00000001 to dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca from the account default

* This action is NOT reversible *

Do you confirm (Y/N)?: Y
Creating the transaction: [████████████████████████████████████████] 100% | ETA: 0s
An error occurred while sending the transaction.
 »   Error: Request failed (400) insufficient-balance: Your balance is too low. Add funds to your account first

C:\Users\song>ironfish wallet:balances
Account: default
 Asset Name Asset Id                                                         Confirmed Balance
 ────────── ──────────────────────────────────────────────────────────────── ─────────────────
 cynic      061b3f5d7f98d6108011d13b55bea09b45cd7a384a4fa6366019d139f240165f 0.00000000
 $IRON      d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6 0.00000000
```

### Graffiti

cynic

**Comment by cynic-1** [comment] 2023-01-23 11:47
I checked my wallet balances a few hours later, now the asset balances are displayed as expected. I believe this is a bug resulting from your error handling module which simply display all assets balance to 0 when some error happen.

**Comment by cynic-1** [comment] 2023-01-23 11:52
https://github.com/iron-fish/ironfish/issues/3067#issuecomment-1399567174

According to the issue created before, your guy will fix it in the PR to be merged. Thanks a lot.

**Comment by wd021** [comment] 2023-02-19 19:10
fixed as of latest version, can't reproduce anymore.

**Closed** 2023-02-27 18:07 UTC
Labels: bug, verified
