### ISSUE TITLE
run-time exception

### ISSUE THREAD

**Issue by SunnyBoy00l** [iron-fish/ironfish#1721] opened 2022-07-01 01:28 UTC
/usr/src/app/node_modules/@ironfish/sdk/build/src/account/accounts.js:320
                            throw new Error('nullifierToNote mappings must have a corresponding noteToNullifier map');
                                  ^

Error: nullifierToNote mappings must have a corresponding noteToNullifier map
    at /usr/src/app/node_modules/ESC[4m@ironfishESC[24m/sdk/build/src/account/accounts.js:320:35
    at async LevelupDatabase.withTransaction (/usr/src/app/node_modules/ESC[4m@ironfishESC[24m/sdk/build/src/storage/database/database.js:39:28)

**Comment by SunnyBoy00l** [comment] 2022-07-01 01:30
name       ironfish
version    0.1.37
git        44a7990
runtime    node/16.15.1


In the new version, I often encounter an abnormal exit of the running program. As mentioned in the log above, this problem also exists in the historical version, but it is more frequent in the current version. Could the project team help to solve the program stability later

**Comment by Shekelme** [comment] 2022-07-15 14:37
Still the same with 0.1.38

**Comment by lwisne** [comment] 2022-08-03 17:15
What command(s) are you running when this happens? What is your `ironfish debug` output?

**Comment by lwisne** [comment] 2022-08-04 18:53
Duplicate of https://github.com/iron-fish/ironfish/issues/1500

**Closed by lwisne** 2022-08-04 18:53 UTC
Labels: bug, needs verification
