### ISSUE TITLE
[issue name] gc error

### ISSUE THREAD

**Issue by hbhdhxl** [iron-fish/ironfish#1429] opened 2022-05-17 06:42 UTC
### What happened?

A GC problem occurred when the node was running one end of the time.

### Version

ironfish/0.1.33 linux-x64 node-v16.14.0

### Debug output

```shell
<--- Last few GCs --->

[27375:0x5a68d60] 87067860 ms: Mark-sweep 4033.0 (4142.9) -> 4017.5 (4143.4) MB, 2317.1 / 0.3 ms  (average mu = 0.462, current mu = 0.268) allocation failure scavenge might not succeed
[27375:0x5a68d60] 87075412 ms: Mark-sweep 4033.6 (4143.6) -> 4018.0 (4144.1) MB, 3556.2 / 0.3 ms  (average mu = 0.504, current mu = 0.529) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09980 node::Abort() [node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [node]
 3: 0xcf77be v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcf7b37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xeaf3d5  [node]
 6: 0xebf09d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xec1d9e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xe832da v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
 9: 0x11fc026 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x15f0a99  [node]
```

### Relevant log output

```shell
<--- Last few GCs --->

[27375:0x5a68d60] 87067860 ms: Mark-sweep 4033.0 (4142.9) -> 4017.5 (4143.4) MB, 2317.1 / 0.3 ms  (average mu = 0.462, current mu = 0.268) allocation failure scavenge might not succeed
[27375:0x5a68d60] 87075412 ms: Mark-sweep 4033.6 (4143.6) -> 4018.0 (4144.1) MB, 3556.2 / 0.3 ms  (average mu = 0.504, current mu = 0.529) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb09980 node::Abort() [node]
 2: 0xa1c235 node::FatalError(char const*, char const*) [node]
 3: 0xcf77be v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcf7b37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xeaf3d5  [node]
 6: 0xebf09d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xec1d9e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xe832da v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
 9: 0x11fc026 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x15f0a99  [node]
```

### Graffiti

xjfk

**Comment by lwisne** [comment] 2022-08-03 23:36
Duplicate of https://github.com/iron-fish/ironfish/issues/1925

**Closed by lwisne** 2022-08-03 23:36 UTC
Labels: bug, verified
