### ISSUE TITLE
Frequently Expiring Deposits - Fee=2000

### ISSUE THREAD

**Issue by airj1012** [iron-fish/ironfish#2372] opened 2022-10-18 14:11 UTC
### What happened?

I've processed 60+ completed transactions in the past hour yet have only received 2 points. The deposits are expiring too frequently. I have the fee set at 2000. Expiration is default. Below are a few transaction hashes for reference.

148f11692025a68efa83515a581827d5d3425ca0d129c9bbf67e2c323e5a22e2
21e31509ffd3c7c2f4151d6d83e29e5c40b670838313a7242086d0f4c7407bb9
54adf3fb677e5b75f6e3728cbdce71ef386a19889fc311a121ac84cbed68c8ce
d80af95193e3594b310bfcd413819b319b1d7e8b2998db8244d8e75ec2e46741

![Untitled-12](https://user-images.githubusercontent.com/64874325/196454806-d9fffe81-ff42-4cb4-909e-5f0236ff2c98.png)

### Version

0.1.49

### Graffiti

airj1012

**Comment by hughy** [comment] 2022-11-02 22:46
It's possible that network congestion is responsible for these expirations. If the transactions were not gossiped to miners quickly enough then miners would not have been able to mine these transactions in blocks.

We're hopeful that increasing the maximum deposit amount will reduce network congestion over the next two weeks!

**Comment by hughy** [comment] 2022-12-08 23:02
Based on other issues it looks like you were able to get some transactions confirmed!

I'm going to close this issue, but please open a new issue if you run into similar issues in the future!

**Closed by hughy** 2022-12-08 23:02 UTC
Labels: bug
