### ISSUE TITLE
Error: getLatestHeadHash: No header found

### ISSUE THREAD

**Issue by luoam** [iron-fish/ironfish#2557] opened 2022-11-12 01:52 UTC
### What happened?

first time run  ironfish start --datadir=E:\ironfish-testnet  on a new node, it display an error.
![Screenshot from 2022-11-12 09-51-40](https://user-images.githubusercontent.com/22240627/201450988-a19ec9d4-5b6c-4b70-8cfb-32334fcd4575.png)

### Version

0.1.49 @ ec57ed3

### Debug output

```shell
Error: Database is not open. Call IDatabase.open() first
    at LevelupDatabase.get levelup [as levelup] (C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\storage\levelup\database.js:31:19)
    at LevelupStore.getAllIter (C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\storage\levelup\store.js:82:32)
    at getAllIter.next (<anonymous>)
    at WalletDB.loadHeadHashes (C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\node_modules\@ironfish\sdk\build\src\wallet\walletdb\walletdb.js:137:46)
    at loadHeadHashes.next (<anonymous>)
    at Debug.outputRequiringDB (C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\build\src\commands\debug.js:77:48)
    at Debug.start (C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\build\src\commands\debug.js:37:57)
    at async Debug.run (C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\build\src\command.js:24:13)
    at async Debug._run (C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\node_modules\@oclif\core\lib\command.js:81:22)
    at async Config.runCommand (C:\Users\admin\AppData\Roaming\npm\node_modules\ironfish\node_modules\@oclif\core\lib\config\config.js:272:25)
```

### Graffiti

maoul

**Comment by hughy** [comment] 2022-11-12 04:16
This is caused by a bug that was fixed in version 0.1.50: https://github.com/iron-fish/ironfish/pull/2462

Updating to the latest version (0.1.51) should resolve this for you!

**Closed** 2022-11-12 16:02 UTC
Labels: bug
