### ISSUE TITLE
POLYHASH

### ISSUE THREAD

**Issue by tokenmoon** [iron-fish/ironfish#1302] opened 2022-05-10 22:41 UTC
### What happened?

Failed to install Ironfish on Ubunto.

### Version

Ubuntu 20.14

### Debug output

```shell
npm ERR! code EINTEGRITY
npm ERR! sha512-kYkgOeUF7ow9QHG1rv+HQg8c+9KWjS5gGvoWWoCiTcbzQ1hoq5IJGYFSjJCvnSQUqcqu9ZXAWYKeUxSXVFAtSA== integrity checksum failed when using sha512: wanted sha512-kYkgOeUF7ow9QHG1rv+HQg8c+9KWjS5gGvoWWoCiTcbzQ1hoq5IJGYFSjJCvnSQUqcqu9ZXAWYKeUxSXVFAtSA== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
/usr/local/bin/ironfish -> /usr/local/lib/node_modules/ironfish/bin/run

> bcrypto@5.5.0 install /usr/local/lib/node_modules/ironfish/node_modules/bcrypto
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ironfish/node_modules/bcrypto/build'
gyp ERR! System Linux 5.4.0-107-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ironfish/node_modules/bcrypto
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
npm WARN notsup Unsupported engine for ironfish@0.1.32: wanted: {"node":"16.x"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: ironfish@0.1.32
npm WARN notsup Unsupported engine for @oclif/plugin-help@5.1.12: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @oclif/plugin-help@5.1.12
npm WARN notsup Unsupported engine for @oclif/plugin-not-found@2.3.1: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @oclif/plugin-not-found@2.3.1
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs@0.1.6
npm WARN notsup Unsupported engine for @oclif/core@1.6.1: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @oclif/core@1.6.1
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-linux-x64-gnu@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-linux-x64-gnu@0.1.6
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-darwin-x64@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-darwin-x64@0.1.6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ironfish/rust-nodejs-darwin-x64@0.1.6 (node_modules/ironfish/node_modules/@ironfish/rust-nodejs/node_modules/@ironfish/rust-nodejs-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ironfish/rust-nodejs-darwin-x64@0.1.6: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-linux-arm64-gnu@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-linux-arm64-gnu@0.1.6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ironfish/rust-nodejs-linux-arm64-gnu@0.1.6 (node_modules/ironfish/node_modules/@ironfish/rust-nodejs/node_modules/@ironfish/rust-nodejs-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ironfish/rust-nodejs-linux-arm64-gnu@0.1.6: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-linux-arm64-musl@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-linux-arm64-musl@0.1.6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ironfish/rust-nodejs-linux-arm64-musl@0.1.6 (node_modules/ironfish/node_modules/@ironfish/rust-nodejs/node_modules/@ironfish/rust-nodejs-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ironfish/rust-nodejs-linux-arm64-musl@0.1.6: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-linux-x64-musl@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-linux-x64-musl@0.1.6
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-darwin-arm64@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-darwin-arm64@0.1.6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ironfish/rust-nodejs-darwin-arm64@0.1.6 (node_modules/ironfish/node_modules/@ironfish/rust-nodejs/node_modules/@ironfish/rust-nodejs-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ironfish/rust-nodejs-darwin-arm64@0.1.6: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-win32-x64-msvc@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-win32-x64-msvc@0.1.6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ironfish/rust-nodejs-win32-x64-msvc@0.1.6 (node_modules/ironfish/node_modules/@ironfish/rust-nodejs/node_modules/@ironfish/rust-nodejs-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ironfish/rust-nodejs-win32-x64-msvc@0.1.6: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-darwin-arm64@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-darwin-arm64@1.3.1: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-win32-arm64-msvc@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-win32-arm64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-win32-arm64-msvc@1.3.1: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-android-arm-eabi@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-android-arm-eabi):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-android-arm-eabi@1.3.1: wanted {"os":"android","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-android-arm64@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-android-arm64@1.3.1: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-darwin-x64@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-darwin-x64@1.3.1: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-linux-arm64-musl@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-linux-arm64-musl@1.3.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-linux-arm64-gnu@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-linux-arm64-gnu@1.3.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-linux-arm-gnueabihf@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-linux-arm-gnueabihf@1.3.1: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-win32-x64-msvc@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-win32-x64-msvc@1.3.1: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-win32-ia32-msvc@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-win32-ia32-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-win32-ia32-msvc@1.3.1: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-freebsd-x64@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-freebsd-x64@1.3.1: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for npmlog@6.0.2: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: npmlog@6.0.2
npm WARN notsup Unsupported engine for gauge@4.0.4: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: gauge@4.0.4
npm WARN notsup Unsupported engine for are-we-there-yet@3.0.0: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: are-we-there-yet@3.0.0
npm WARN notsup Unsupported engine for @oclif/screen@3.0.2: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @oclif/screen@3.0.2
npm WARN notsup Unsupported engine for @oclif/color@1.0.1: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @oclif/color@1.0.1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypto@5.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypto@5.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-10T22_35_05_497Z-debug.log
```

### Relevant log output

```shell
npm ERR! code EINTEGRITY
npm ERR! sha512-kYkgOeUF7ow9QHG1rv+HQg8c+9KWjS5gGvoWWoCiTcbzQ1hoq5IJGYFSjJCvnSQUqcqu9ZXAWYKeUxSXVFAtSA== integrity checksum failed when using sha512: wanted sha512-kYkgOeUF7ow9QHG1rv+HQg8c+9KWjS5gGvoWWoCiTcbzQ1hoq5IJGYFSjJCvnSQUqcqu9ZXAWYKeUxSXVFAtSA== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
/usr/local/bin/ironfish -> /usr/local/lib/node_modules/ironfish/bin/run

> bcrypto@5.5.0 install /usr/local/lib/node_modules/ironfish/node_modules/bcrypto
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ironfish/node_modules/bcrypto/build'
gyp ERR! System Linux 5.4.0-107-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ironfish/node_modules/bcrypto
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
npm WARN notsup Unsupported engine for ironfish@0.1.32: wanted: {"node":"16.x"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: ironfish@0.1.32
npm WARN notsup Unsupported engine for @oclif/plugin-help@5.1.12: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @oclif/plugin-help@5.1.12
npm WARN notsup Unsupported engine for @oclif/plugin-not-found@2.3.1: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @oclif/plugin-not-found@2.3.1
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs@0.1.6
npm WARN notsup Unsupported engine for @oclif/core@1.6.1: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @oclif/core@1.6.1
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-linux-x64-gnu@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-linux-x64-gnu@0.1.6
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-darwin-x64@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-darwin-x64@0.1.6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ironfish/rust-nodejs-darwin-x64@0.1.6 (node_modules/ironfish/node_modules/@ironfish/rust-nodejs/node_modules/@ironfish/rust-nodejs-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ironfish/rust-nodejs-darwin-x64@0.1.6: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-linux-arm64-gnu@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-linux-arm64-gnu@0.1.6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ironfish/rust-nodejs-linux-arm64-gnu@0.1.6 (node_modules/ironfish/node_modules/@ironfish/rust-nodejs/node_modules/@ironfish/rust-nodejs-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ironfish/rust-nodejs-linux-arm64-gnu@0.1.6: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-linux-arm64-musl@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-linux-arm64-musl@0.1.6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ironfish/rust-nodejs-linux-arm64-musl@0.1.6 (node_modules/ironfish/node_modules/@ironfish/rust-nodejs/node_modules/@ironfish/rust-nodejs-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ironfish/rust-nodejs-linux-arm64-musl@0.1.6: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-linux-x64-musl@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-linux-x64-musl@0.1.6
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-darwin-arm64@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-darwin-arm64@0.1.6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ironfish/rust-nodejs-darwin-arm64@0.1.6 (node_modules/ironfish/node_modules/@ironfish/rust-nodejs/node_modules/@ironfish/rust-nodejs-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ironfish/rust-nodejs-darwin-arm64@0.1.6: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for @ironfish/rust-nodejs-win32-x64-msvc@0.1.6: wanted: {"node":">= 16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @ironfish/rust-nodejs-win32-x64-msvc@0.1.6
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ironfish/rust-nodejs-win32-x64-msvc@0.1.6 (node_modules/ironfish/node_modules/@ironfish/rust-nodejs/node_modules/@ironfish/rust-nodejs-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ironfish/rust-nodejs-win32-x64-msvc@0.1.6: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-darwin-arm64@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-darwin-arm64@1.3.1: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-win32-arm64-msvc@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-win32-arm64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-win32-arm64-msvc@1.3.1: wanted {"os":"win32","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-android-arm-eabi@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-android-arm-eabi):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-android-arm-eabi@1.3.1: wanted {"os":"android","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-android-arm64@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-android-arm64@1.3.1: wanted {"os":"android","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-darwin-x64@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-darwin-x64@1.3.1: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-linux-arm64-musl@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-linux-arm64-musl):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-linux-arm64-musl@1.3.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-linux-arm64-gnu@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-linux-arm64-gnu):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-linux-arm64-gnu@1.3.1: wanted {"os":"linux","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-linux-arm-gnueabihf@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-linux-arm-gnueabihf):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-linux-arm-gnueabihf@1.3.1: wanted {"os":"linux","arch":"arm"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-win32-x64-msvc@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-win32-x64-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-win32-x64-msvc@1.3.1: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-win32-ia32-msvc@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-win32-ia32-msvc):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-win32-ia32-msvc@1.3.1: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @napi-rs/blake-hash-freebsd-x64@1.3.1 (node_modules/ironfish/node_modules/@napi-rs/blake-hash/node_modules/@napi-rs/blake-hash-freebsd-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @napi-rs/blake-hash-freebsd-x64@1.3.1: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for npmlog@6.0.2: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: npmlog@6.0.2
npm WARN notsup Unsupported engine for gauge@4.0.4: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: gauge@4.0.4
npm WARN notsup Unsupported engine for are-we-there-yet@3.0.0: wanted: {"node":"^12.13.0 || ^14.15.0 || >=16"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: are-we-there-yet@3.0.0
npm WARN notsup Unsupported engine for @oclif/screen@3.0.2: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @oclif/screen@3.0.2
npm WARN notsup Unsupported engine for @oclif/color@1.0.1: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: @oclif/color@1.0.1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypto@5.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypto@5.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-10T22_35_05_497Z-debug.log
```

### Graffiti

POLYHASH

**Comment by lwisne** [comment] 2022-07-26 21:18
Closing due to lack of update + inability to reproduce.

**Closed by lwisne** 2022-07-26 21:18 UTC
Labels: bug
