### ISSUE TITLE
Node Crashed

### ISSUE THREAD

**Issue by aditya-manit** [iron-fish/ironfish#689] opened 2021-12-10 15:55 UTC
My node crashed with the logs
```
Added block to fork seq: 16238, head-seq: 16238, hash: 00000...95d80, head-hash: 00000...ba89d, work: 1240787706690227, head-work: 1240787706690227, work-diff: 0
Added block seq: 16240, hash: 00000...369bb, txs: 1, progress: 100.00%, time: 96.0ms
Added block to fork seq: 16241, head-seq: 16241, hash: 00000...29b0f, head-hash: 00000...257de, work: 1240923492388141, head-work: 1240923492388141, work-diff: 0
/usr/src/app/node_modules/ironfish/build/src/blockchain/blockchain.js:569
                    throw new Error(verification.reason);
                          ^

Error: Transaction expired
    at /usr/src/app/node_modules/ironfish/build/src/blockchain/blockchain.js:569:27
    at async LevelupDatabase.withTransaction (/usr/src/app/node_modules/ironfish/build/src/storage/database/database.js:39:28)
    at async Blockchain.newBlock (/usr/src/app/node_modules/ironfish/build/src/blockchain/blockchain.js:519:16)
    at async MiningDirector.constructAndMineBlock (/usr/src/app/node_modules/ironfish/build/src/mining/director.js:257:26)
    at async MiningDirector.constructAndMineBlockWithRetry (/usr/src/app/node_modules/ironfish/build/src/mining/director.js:200:26)
    ```

**Comment by zkstorm** [comment] 2021-12-10 18:19
I also encountered this.

**Comment by Megavolv** [comment] 2021-12-10 18:45
Me too:
Invalid block adding to fork 00000...c8b84 (15823): Transaction expired
Peer jmKvf1b (muravei8) sent an invalid block. score: 10, hash: 00000...c8b84 (
          15823
        ), reason: Transaction expired
Peer jmKvf1b (muravei8) has been banned: Transaction expired

**Comment by dguenther** [comment] 2021-12-11 01:44
Closing as a duplicate of #652, please feel free to add comments there.

**Closed by dguenther** 2021-12-11 01:44 UTC
