### ISSUE TITLE
asset balance decreased even though ironfish:wallet send command failed

### ISSUE THREAD

**Issue by leowgriffin** [iron-fish/ironfish#3403] opened 2023-02-13 14:25 UTC
### What happened?

I sent out 2 successful commands on minting and burning assets before trying to send the asset to the official ironbank address. 
The first attempt failed and returned a message:
> Not enough unspent notes available to fund the transaction. Please wait for any pending transactions to be confirmed.

So I waited for a few minutes before trying again. For the second attempt, it seems that my asset balance decreased by 1 even though the first attempt failed.

Attaching screenshot for more clarity.
![ironfish_bug](https://user-images.githubusercontent.com/36526975/218483393-af38ebd7-10fd-49e6-82e2-2622f7489c05.jpg)

### Version

ironfish/0.1.65 win32-x64 node-v18.13.0

### Graffiti

ayanami

**Comment by ygao76** [comment] 2023-02-13 19:15
Is there any transaction you made before your first attempt of `wallet:send`? You mentioned you made mint and burn. 
In the first attempt message, there are pending transactions to be confirmed. So those transaction is processed and confirmed when you made the second attempt. The reduced balance is from those transaction, not from the first attempt.

**Comment by holahula** [comment] 2023-04-20 22:44
Closing due to staleness. If the issue persists in versions `1.0.0+` - please file a new issue

**Closed by holahula** 2023-04-20 22:44 UTC
Labels: bug
