### ISSUE TITLE
mined 12 blocks, status: fork

### ISSUE THREAD

**Issue by kdolli072** [iron-fish/ironfish#742] opened 2021-12-14 07:30 UTC
Good day!
My graffiti on leaderboard: kdolli072
I mined 12 blocks on the IronFish testnet.
All 12 blocks were found to be illiquid. Block status - fork.
Help fix the situation.
The operating system UBUNTU 20.04 and the IronFish miner reinstalled, the problem was not solved.

**Comment by gjfrn** [comment] 2021-12-20 00:38
Duplicate of #731

**Comment by lwisne** [comment] 2022-07-23 02:05
We think this is fixed now. Closing. Let me know if you believe otherwise.

**Closed by lwisne** 2022-07-23 02:05 UTC
