### ISSUE TITLE
sudden Node out of JS memory after running fine for 2.5 weeks: FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by crProductGuy** [iron-fish/ironfish#1678] opened 2022-06-27 01:56 UTC
Full text here is also in the attached .txt file

Out of JS Memory node crash Sunday 26jun22
Error message:
FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory

 - Significance: sudden problem when there had been plenty of available RAM
 
Had been using 5.1-5.3 GB of 5.9GB available for more than a day of continuous node running since last node start.

Same config had been running successfully for over 2.5 weeks without any node crashes and > 0.5 GB free RAM.  

Only other thing running was a few browser tabs in the background.

Environment: Window 10, iron fish 0.1.36 installation via npm
Version 0.1.36 @ 6dfc736
2-core Athlon Silver HP laptop, 3.06 GHz

-=-=-=-=-=-=-=

`Ironfish Debug` output:

Iron Fish version            0.1.36 @ 6dfc736
Iron Fish library            0.0.14 @ 6dfc736
Operating system             Windows_NT x64
CPU model(s)                 AMD Athlon Silver 3050U with Radeon Graphics
CPU threads                  2
RAM total                    5.88 GiB
Node version                 v16.15.1
ironfish in PATH             true
Telemetry enabled            true
Accounts head hash           0000000000030323ea58c96b56642b6e5f3fb45d6e55825edc094309ae8e6811
Accounts head in chain       true
Accounts head sequence       67795

-=-=-=-=-=-=-=-=-=-=-

Node log history before and after crash:

Added block to fork seq: 67924, head-seq: 67924, hash: 00000...599dd, head-hash: 00000...76e65, work: 1486454041963519559, head-work: 1486454063520049381, work-diff: 21556529822
Added block to fork seq: 67926, head-seq: 67927, hash: 00000...b69ce, head-hash: 00000...391ea, work: 1486498146581496869, head-work: 1486520371384651913, work-diff: 22224803155044
Reorganizing chain from 00000...c21f2 (67930) for 00000...08cc1 (67930) on prev 00000...d5886 (67929)
Reorganized chain. blocks: 1, old: 00000...c21f2 (67930), new: 00000...d5886 (67929), fork: 00000...d5886 (67929)
Reorganizing chain from 00000...08cc1 (67930) for 00000...12339 (67931) on prev 00000...c21f2 (67930)
Reorganized chain. blocks: 2, old: 00000...08cc1 (67930), new: 00000...c21f2 (67930), fork: 00000...d5886 (67929)
Added block to fork seq: 67931, head-seq: 67931, hash: 00000...4a70c, head-hash: 00000...12339, work: 1486608827586197589, head-work: 1486608859936193601, work-diff: 32349996012
Added block seq: 67940, hash: 00000...33e5a, txs: 102, progress: 99.97%, time: 18543.2ms

<--- Last few GCs --->

[3944:000001A2787AC000] 227322127 ms: Scavenge 13.1 (15.6) -> 12.2 (15.6) MB, 34.6 / 10.3 ms  (average mu = 1.000, current mu = 1.000) task
[3944:000001A2787AC000] 227332557 ms: Scavenge 13.0 (15.6) -> 12.2 (15.6) MB, 0.6 / 0.0 ms  (average mu = 1.000, current mu = 1.000) task
[3944:000001A2787AC000] 227344729 ms: Scavenge 13.2 (15.6) -> 12.2 (15.6) MB, 0.3 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure

<--- JS stacktrace --->

FATAL ERROR: Committing semi space failed. Allocation failed - JavaScript heap out of memory
 1: 00007FF61C8979CF
 2: 00007FF61C826096
 3: 00007FF61C826F4D
 4: 00007FF61D15B1EE
 5: 00007FF61D1457CD
 6: 00007FF61CFE8B9C
 7: 00007FF61CFF28BF
 8: 00007FF61CFE5479
 9: 00007FF61CFE3630
10: 00007FF61D0081B6
11: 00007FF61CD3A685
12: 00007FF61D1E8EE1
13: 00007FF61D255D68
14: 000001A200123E8F

[Out of JS Memory node crash Sunday 26jun22.txt](https://github.com/iron-fish/ironfish/files/8988094/Out.of.JS.Memory.node.crash.Sunday.26jun22.txt)

**Comment by lwisne** [comment] 2022-08-03 18:56
adding to the heap of memory errors

**Comment by lwisne** [comment] 2022-08-03 23:39
Duplicate of https://github.com/iron-fish/ironfish/issues/1925

**Closed by lwisne** 2022-08-03 23:39 UTC
Labels: bug, verified
