### ISSUE TITLE
Problem with mining

### ISSUE THREAD

**Issue by Mayovka** [iron-fish/ironfish#1098] opened 2022-03-08 10:58 UTC
### What happened?

as I understand the error, the ignition disappears all the time, this week because of nothing it was mined, the solution to the problem is quite simple, you need to run the command " systemctl restart ironfishd ironfishd-miner " 
![photo_2022-03-08_12-48-42](https://user-images.githubusercontent.com/95088734/157225264-dcd3fc81-d77f-4a21-9824-d9224cb16536.jpg)
 

### Version

0.1.25

**Comment by Kupuyc** [comment] 2022-03-08 13:20
Duplicate of #928.

**Comment by holahula** [comment] 2023-04-20 22:17
Closing due to staleness. If the issue persists - please file a new issue

**Closed by holahula** 2023-04-20 22:17 UTC
Labels: bug, verified
